#############################################################################
# Makefile for building ezxfba/ezxfba
# Generated by tmake at 17:09, 2007/03/31
#     Project: ezxfba
#    Template: app
# *** HAND EDITED ***
#############################################################################

####### Compiler, tools and options

CC	=	arm-linux-gnueabihf-gcc
CXX	=	arm-linux-gnueabihf-g++
CFLAGS	= -march=armv6 -mfpu=vfp -mfloat-abi=hard -pipe -Wall -W -O3 -DOOPSWARE_FIX -D_T="" -DNEOGEO_HACKS -D__cdecl="" -D__fastcall="" -DUSE_SPEEDHACKS -DNEO_DISPLAY_OVERSCAN 
CFLAGS += -falign-functions=32 -falign-loops -falign-labels -falign-jumps -fomit-frame-pointer -ffast-math -fexpensive-optimizations -finline -finline-functions
CFLAGS += -mstructure-size-boundary=32 -frename-registers 
CFLAGSPROFILE = -mcpu=arm920t -mtune=arm920t -pipe -Wall -W -O3 -DOOPSWARE_FIX -D_T="" -DNEOGEO_HACKS -D__cdecl="" -D__fastcall="" -DUSE_SPEEDHACKS -DNEO_DISPLAY_OVERSCAN 
CFLAGSPROFILE += -falign-functions=32 -falign-loops -falign-labels -falign-jumps -fomit-frame-pointer -ffast-math -fexpensive-optimizations -finline -finline-functions
CFLAGSPROFILE += -mstructure-size-boundary=32 -frename-registers 
CXXFLAGS= -march=armv6 -mfpu=vfp -mfloat-abi=hard -pipe -DQWS -fno-exceptions -fno-rtti -Wall -W -O3 -DOOPSWARE_FIX -D_T="" -DNEOGEO_HACKS -D__cdecl="" -D__fastcall="" -DUSE_SPEEDHACKS -DNEO_DISPLAY_OVERSCAN 
CXXFLAGS += -falign-functions=32 -falign-loops -falign-labels -falign-jumps -fomit-frame-pointer -ffast-math -fexpensive-optimizations -finline -finline-functions
CXXFLAGS += -mstructure-size-boundary=32 -frename-registers 
CXXFLAGSPROFILE= -mcpu=arm920t -mtune=arm920t -pipe -DQWS -fno-exceptions -fno-rtti -Wall -W -O3 -DOOPSWARE_FIX -D_T="" -DNEOGEO_HACKS -D__cdecl="" -D__fastcall="" -DUSE_SPEEDHACKS -DNEO_DISPLAY_OVERSCAN 
CXXFLAGSPROFILE += -falign-functions=32 -falign-loops -falign-labels -falign-jumps -fomit-frame-pointer -ffast-math -fexpensive-optimizations -finline -finline-functions
CXXFLAGSPROFILE += -mstructure-size-boundary=32 -frename-registers 
INCPATH	= -I. -I./burn -I./burn/neogeo -I./burn/capcom -I./burn/cave -I./burn/toaplan -I./cpu/cz80 -I./cpu/cyclone -I./cpu/z80 -I./cpu/nec -I./cpu/sh2 -I./burn/misc -I$(EZX_BASE)/include/3pt -I$(EZX_BASE)/include/qt -I$(EZX_BASE)/include/ezx -I$(SDKSTAGE)/opt/vc/include -I$(SDKSTAGE)/opt/vc/include/interface/vcos/pthreads \
	-I$(SDKSTAGE)/opt/vc/include/interface/vmcs_host/linux -I/usr/include/SDL -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include 
LINK	= arm-linux-gnueabihf-g++
LFLAGS	= 
LIBS	= -lz -lpthread -lm -lpthread -lSDL -L/opt/vc/lib -lbcm_host -lGLESv2 -lEGL -lglib-2.0

TAR	=	tar -cf
GZIP	=	gzip -9f

OBJ = .obj

####### Files

HEADERS = gp2xsdk.h \
		main.h \
		configfile.h \
		gamewidget.h \
		ezxaudio.h \
		fba_player.h \
		font.h \
		snd.h \
		z80.h \
		cyclone.h \
		burn.h \
		burnint.h \
		stdfunc.h \
		ay8910.h \
		burn_ym2151.h \
		burn_ym2608.h \
		burn_ym2610.h \
		burn_ym3812.h \
		burn_ymf278b.h \
		eeprom_93cxx.h \
		fm.h \
		fmopl.h \
		msm5205.h \
		msm6295.h \
		timer.h \
		ym2151.h \
		ymdeltat.h \
		ymf278b.h \
		ymz280b.h \
		burn_sound.h \
		burn.h \
		sek.h \
		zet.h \
		cps.h \
		neogeo.h \
		cave.h \
		toaplan.h \
		cache.h
SOURCES = gp2xsdk.cpp \
		gles2.cpp \
		thread.c \
		fifo_buffer.c \
		main.cpp \
		gamewidget.cpp \
		ezxaudio.cpp \
		fba_player.cpp \
		font.cpp \
		snd.cpp \
		cache.cpp \
		cpu/cz80/cz80.c \
		cpu/cyclone/cyclone.s \
		cpu/z80/z80.cpp \
		cpu/nec/nec.cpp \
		cpu/nec/sh2.cpp \
		burn/ay8910.c \
		burn/burn_ym2151.cpp \
		burn/burn_ym2610.cpp \
		burn/burn_ym3812.cpp \
		burn/burn_ym2203.cpp \
		burn/burn_ym2608.cpp \
		burn/burn_ymf278b.cpp \
		burn/eeprom_93cxx.cpp \
		burn/fm.c \
		burn/fmopl.c \
		burn/msm5205.cpp \
		burn/msm6295.cpp \
		burn/timer.cpp \
		burn/ym2151.c \
		burn/ymdeltat.c \
		burn/ymf278b.c \
		burn/ymz280b.cpp \
		burn/burn_sound.cpp \
		burn/burn_sound_c.cpp \
		burn/burn.cpp \
		burn/load.cpp \
		burn/sek.cpp \
		burn/czet.cpp \
		burn/zet.cpp \
		burn/vez.cpp \
		burn/capcom/cps.cpp \
		burn/capcom/cps_draw.cpp \
		burn/capcom/cps_mem.cpp \
		burn/capcom/cps2_crpt.cpp \
		burn/capcom/cps_obj.cpp \
		burn/capcom/cps_pal.cpp \
		burn/capcom/cps_run.cpp \
		burn/capcom/cps_rw.cpp \
		burn/capcom/cps_scr.cpp \
		burn/capcom/cpsr.cpp \
		burn/capcom/cpsrd.cpp \
		burn/capcom/cpst.cpp \
		burn/capcom/ctv.cpp \
		burn/capcom/dc_3wonders.cpp \
		burn/capcom/dc_19xx.cpp \
		burn/capcom/dc_1941.cpp \
		burn/capcom/dc_1944.cpp \
		burn/capcom/dc_armwar.cpp \
		burn/capcom/dc_avsp.cpp \
		burn/capcom/dc_batcir.cpp \
		burn/capcom/dc_captcomm.cpp \
		burn/capcom/dc_cawing.cpp \
		burn/capcom/dc_choko.cpp \
		burn/capcom/dc_csclub.cpp \
		burn/capcom/dc_cworld2j.cpp \
		burn/capcom/dc_cyb.cpp \
		burn/capcom/dc_ddsom.cpp \
		burn/capcom/dc_ddtod.cpp \
		burn/capcom/dc_dimahoo.cpp \
		burn/capcom/dc_dino.cpp \
		burn/capcom/dc_dstlk.cpp \
		burn/capcom/dc_dw.cpp \
		burn/capcom/dc_ecofghtr.cpp \
		burn/capcom/dc_ffight.cpp \
		burn/capcom/dc_forgottn.cpp \
		burn/capcom/dc_ghouls.cpp \
		burn/capcom/dc_gigawing.cpp \
		burn/capcom/dc_hsf2.cpp \
		burn/capcom/dc_input.cpp \
		burn/capcom/dc_jyangoku.cpp \
		burn/capcom/dc_knights.cpp \
		burn/capcom/dc_kod.cpp \
		burn/capcom/dc_megaman2.cpp \
		burn/capcom/dc_megaman.cpp \
		burn/capcom/dc_mercs.cpp \
		burn/capcom/dc_mmatrix.cpp \
		burn/capcom/dc_mpang.cpp \
		burn/capcom/dc_msh.cpp \
		burn/capcom/dc_mshvsf.cpp \
		burn/capcom/dc_msword.cpp \
		burn/capcom/dc_mtwins.cpp \
		burn/capcom/dc_mvsc.cpp \
		burn/capcom/dc_nemo.cpp \
		burn/capcom/dc_nwarr.cpp \
		burn/capcom/dc_pang3.cpp \
		burn/capcom/dc_pnickj.cpp \
		burn/capcom/dc_progear.cpp \
		burn/capcom/dc_punisher.cpp \
		burn/capcom/dc_pzloop2.cpp \
		burn/capcom/dc_qad.cpp \
		burn/capcom/dc_qnd.cpp \
		burn/capcom/dc_qtono2.cpp \
		burn/capcom/dc_ringdest.cpp \
		burn/capcom/dc_sf2.cpp \
		burn/capcom/dc_sf2t.cpp \
		burn/capcom/dc_sfa2.cpp \
		burn/capcom/dc_sfa3.cpp \
		burn/capcom/dc_sfa.cpp \
		burn/capcom/dc_sfzch.cpp \
		burn/capcom/dc_sgemf.cpp \
		burn/capcom/dc_slammast.cpp \
		burn/capcom/dc_spf.cpp \
		burn/capcom/dc_ssf2.cpp \
		burn/capcom/dc_ssf2t.cpp \
		burn/capcom/dc_strider.cpp \
		burn/capcom/dc_unsquad.cpp \
		burn/capcom/dc_varth.cpp \
		burn/capcom/dc_vhunt2.cpp \
		burn/capcom/dc_vsav2.cpp \
		burn/capcom/dc_vsav.cpp \
		burn/capcom/dc_willow.cpp \
		burn/capcom/dc_wof.cpp \
		burn/capcom/dc_xmcota.cpp \
		burn/capcom/dc_xmvsf.cpp \
		burn/capcom/kabuki.cpp \
		burn/capcom/ps.cpp \
		burn/capcom/ps_m.cpp \
		burn/capcom/ps_z.cpp \
		burn/capcom/qs.cpp \
		burn/capcom/qs_c.cpp \
		burn/capcom/qs_z.cpp \
		burn/cps3/cps3run.cpp \
		burn/cps3/cps3snd.cpp \
		burn/cps3/d_cps3.cpp \
		burn/cps3/d_psikyosh.cpp \
		burn/cps3/d_suprnova.cpp \
		burn/neogeo/neo_decrypt.cpp \
		burn/neogeo/neo_palette.cpp \
		burn/neogeo/neo_run.cpp \
		burn/neogeo/neo_sprite.cpp \
		burn/neogeo/neo_text.cpp \
		burn/neogeo/neo_upd4990a.cpp \
		burn/neogeo/neogeo.cpp \
		burn/neogeo/d_neogeo.cpp \
		burn/misc/d_parent.cpp \
		burn/misc/d_aerofgt.cpp \
		burn/misc/d_galpanic.cpp \
		burn/misc/d_wwfwfest.cpp \
		burn/misc/d_biomtoy.cpp \
		burn/misc/d_bombjack.cpp \
		burn/misc/d_hyperpac.cpp \
		burn/misc/d_kaneko16.cpp \
		burn/misc/d_fstarfrc.cpp \
		burn/misc/d_powerins.cpp \
		burn/misc/d_news.cpp \
		burn/misc/d_ohmygod.cpp \
		burn/misc/d_wc90.cpp \
		burn/misc/d_m92.cpp \
		burn/misc/d_1945kiii.cpp \
		burn/misc/d_tumbleb.cpp \
		burn/misc/d_gaiden.cpp \
		burn/misc/d_unico.cpp \
		burn/misc/d_esd16.cpp \
		burn/misc/tiles_generic.cpp \
		burn/pgm/d_pgm.cpp \
		burn/pgm/pgm_crypt.cpp \
		burn/pgm/pgm_draw.cpp \
		burn/pgm/pgm_prot.cpp \
		burn/pgm/pgm_run.cpp \
		burn/pgm/pgm_snd.cpp \
		burn/cave/cave.cpp \
		burn/cave/cave_palette.cpp \
		burn/cave/cave_sprite.cpp \
		burn/cave/cave_tile.cpp \
		burn/cave/d_dodonpachi.cpp \
		burn/cave/d_donpachi.cpp \
		burn/cave/d_esprade.cpp \
		burn/cave/d_feversos.cpp \
		burn/cave/d_gaia.cpp \
		burn/cave/d_guwange.cpp \
		burn/cave/d_sailormn.cpp \
		burn/cave/d_uopoko.cpp \
		burn/cave/d_hotdogst.cpp \
		burn/cave/d_mazinger.cpp \
		burn/cave/d_metmqstr.cpp \
		burn/cave/d_pwrinst2.cpp \
		burn/toaplan/toaplan.cpp \
		burn/toaplan/toaplan1.cpp \
		burn/toaplan/toa_palette.cpp \
		burn/toaplan/toa_gp9001.cpp \
		burn/toaplan/toa_extratext.cpp \
		burn/toaplan/toa_bcu2.cpp \
		burn/toaplan/d_batrider.cpp \
		burn/toaplan/d_batsugun.cpp \
		burn/toaplan/d_battleg.cpp \
		burn/toaplan/d_bbakraid.cpp \
		burn/toaplan/d_dogyuun.cpp \
		burn/toaplan/d_kbash.cpp \
		burn/toaplan/d_mahoudai.cpp \
		burn/toaplan/d_outzone.cpp \
		burn/toaplan/d_shippumd.cpp \
		burn/toaplan/d_snowbro2.cpp \
		burn/toaplan/d_tekipaki.cpp \
		burn/toaplan/d_truxton2.cpp \
		burn/toaplan/d_vfive.cpp \
		burn/toaplan/d_truxton.cpp \
		burn/toaplan/d_hellfire.cpp \
		burn/toaplan/d_zerowing.cpp \
		unzip.c \
		zipfn.cpp \
		bzip.cpp \
		statec.cpp \
		state.cpp \
		drv.cpp \
		run.cpp \
		input.cpp 
OBJECTS = $(OBJ)/gp2xsdk.o \
		$(OBJ)/gles2.o \
		$(OBJ)/thread.o \
		$(OBJ)/fifo_buffer.o \
		$(OBJ)/main.o \
		$(OBJ)/gamewidget.o \
		$(OBJ)/ezxaudio.o \
		$(OBJ)/fba_player.o \
		$(OBJ)/font.o \
		$(OBJ)/snd.o \
		$(OBJ)/cache.o \
		$(OBJ)/cz80.o \
		$(OBJ)/cyclone.o \
		$(OBJ)/z80.o \
		$(OBJ)/z80daisy.o \
		$(OBJ)/nec.o \
		$(OBJ)/sh2.o \
		$(OBJ)/ay8910.o \
		$(OBJ)/burn_ym2151.o \
		$(OBJ)/burn_ym2610.o \
		$(OBJ)/burn_ym3812.o \
		$(OBJ)/burn_ym2203.o \
		$(OBJ)/burn_ym2608.o \
		$(OBJ)/burn_ymf278b.o \
		$(OBJ)/eeprom_93cxx.o \
		$(OBJ)/fm.o \
		$(OBJ)/fmopl.o \
		$(OBJ)/msm5205.o \
		$(OBJ)/msm6295.o \
		$(OBJ)/timer.o \
		$(OBJ)/ym2151.o \
		$(OBJ)/ymdeltat.o \
		$(OBJ)/ymf278b.o \
		$(OBJ)/ymz280b.o \
		$(OBJ)/burn_sound.o \
		$(OBJ)/burn_sound_c.o \
		$(OBJ)/burn.o \
		$(OBJ)/load.o \
		$(OBJ)/sek.o \
		$(OBJ)/czet.o \
		$(OBJ)/zet.o \
		$(OBJ)/vez.o \
		$(OBJ)/cps.o \
		$(OBJ)/cps_draw.o \
		$(OBJ)/cps_mem.o \
		$(OBJ)/cps2_crpt.o \
		$(OBJ)/cps_obj.o \
		$(OBJ)/cps_pal.o \
		$(OBJ)/cps_run.o \
		$(OBJ)/cps_rw.o \
		$(OBJ)/cps_scr.o \
		$(OBJ)/cpsr.o \
		$(OBJ)/cpsrd.o \
		$(OBJ)/cpst.o \
		$(OBJ)/ctv.o \
		$(OBJ)/dc_3wonders.o \
		$(OBJ)/dc_19xx.o \
		$(OBJ)/dc_1941.o \
		$(OBJ)/dc_1944.o \
		$(OBJ)/dc_armwar.o \
		$(OBJ)/dc_avsp.o \
		$(OBJ)/dc_batcir.o \
		$(OBJ)/dc_captcomm.o \
		$(OBJ)/dc_cawing.o \
		$(OBJ)/dc_choko.o \
		$(OBJ)/dc_csclub.o \
		$(OBJ)/dc_cworld2j.o \
		$(OBJ)/dc_cyb.o \
		$(OBJ)/dc_ddsom.o \
		$(OBJ)/dc_ddtod.o \
		$(OBJ)/dc_dimahoo.o \
		$(OBJ)/dc_dino.o \
		$(OBJ)/dc_dstlk.o \
		$(OBJ)/dc_dw.o \
		$(OBJ)/dc_ecofghtr.o \
		$(OBJ)/dc_ffight.o \
		$(OBJ)/dc_forgottn.o \
		$(OBJ)/dc_ghouls.o \
		$(OBJ)/dc_gigawing.o \
		$(OBJ)/dc_hsf2.o \
		$(OBJ)/dc_input.o \
		$(OBJ)/dc_jyangoku.o \
		$(OBJ)/dc_knights.o \
		$(OBJ)/dc_kod.o \
		$(OBJ)/dc_megaman2.o \
		$(OBJ)/dc_megaman.o \
		$(OBJ)/dc_mercs.o \
		$(OBJ)/dc_mmatrix.o \
		$(OBJ)/dc_mpang.o \
		$(OBJ)/dc_msh.o \
		$(OBJ)/dc_mshvsf.o \
		$(OBJ)/dc_msword.o \
		$(OBJ)/dc_mtwins.o \
		$(OBJ)/dc_mvsc.o \
		$(OBJ)/dc_nemo.o \
		$(OBJ)/dc_nwarr.o \
		$(OBJ)/dc_pang3.o \
		$(OBJ)/dc_pnickj.o \
		$(OBJ)/dc_progear.o \
		$(OBJ)/dc_punisher.o \
		$(OBJ)/dc_pzloop2.o \
		$(OBJ)/dc_qad.o \
		$(OBJ)/dc_qnd.o \
		$(OBJ)/dc_qtono2.o \
		$(OBJ)/dc_ringdest.o \
		$(OBJ)/dc_sf2.o \
		$(OBJ)/dc_sf2t.o \
		$(OBJ)/dc_sfa2.o \
		$(OBJ)/dc_sfa3.o \
		$(OBJ)/dc_sfa.o \
		$(OBJ)/dc_sfzch.o \
		$(OBJ)/dc_sgemf.o \
		$(OBJ)/dc_slammast.o \
		$(OBJ)/dc_spf.o \
		$(OBJ)/dc_ssf2.o \
		$(OBJ)/dc_ssf2t.o \
		$(OBJ)/dc_strider.o \
		$(OBJ)/dc_unsquad.o \
		$(OBJ)/dc_varth.o \
		$(OBJ)/dc_vhunt2.o \
		$(OBJ)/dc_vsav2.o \
		$(OBJ)/dc_vsav.o \
		$(OBJ)/dc_willow.o \
		$(OBJ)/dc_wof.o \
		$(OBJ)/dc_xmcota.o \
		$(OBJ)/dc_xmvsf.o \
		$(OBJ)/kabuki.o \
		$(OBJ)/ps.o \
		$(OBJ)/ps_m.o \
		$(OBJ)/ps_z.o \
		$(OBJ)/qs.o \
		$(OBJ)/qs_c.o \
		$(OBJ)/qs_z.o \
		$(OBJ)/cps3run.o \
		$(OBJ)/cps3snd.o \
		$(OBJ)/d_cps3.o \
		$(OBJ)/d_psikyosh.o \
		$(OBJ)/d_suprnova.o \
		$(OBJ)/neo_decrypt.o \
		$(OBJ)/neo_palette.o \
		$(OBJ)/neo_run.o \
		$(OBJ)/neo_sprite.o \
		$(OBJ)/neo_text.o \
		$(OBJ)/neo_upd4990a.o \
		$(OBJ)/neogeo.o \
		$(OBJ)/d_neogeo.o \
		$(OBJ)/d_parent.o \
		$(OBJ)/d_aerofgt.o \
		$(OBJ)/d_galpanic.o \
		$(OBJ)/d_wwfwfest.o \
		$(OBJ)/d_pgm.o \
		$(OBJ)/pgm_crypt.o \
		$(OBJ)/pgm_draw.o \
		$(OBJ)/pgm_prot.o \
		$(OBJ)/pgm_run.o \
		$(OBJ)/pgm_snd.o \
		$(OBJ)/d_biomtoy.o \
		$(OBJ)/d_bombjack.o \
		$(OBJ)/d_hyperpac.o \
		$(OBJ)/d_kaneko16.o \
		$(OBJ)/d_fstarfrc.o \
		$(OBJ)/d_powerins.o \
		$(OBJ)/d_news.o \
		$(OBJ)/d_ohmygod.o \
		$(OBJ)/d_wc90.o \
		$(OBJ)/d_m92.o \
		$(OBJ)/d_1945kiii.o \
		$(OBJ)/d_tumbleb.o \
		$(OBJ)/d_gaiden.o \
		$(OBJ)/d_unico.o \
		$(OBJ)/d_esd16.o \
		$(OBJ)/tiles_generic.o \
		$(OBJ)/cave.o \
		$(OBJ)/cave_palette.o \
		$(OBJ)/cave_sprite.o \
		$(OBJ)/cave_tile.o \
		$(OBJ)/d_dodonpachi.o \
		$(OBJ)/d_donpachi.o \
		$(OBJ)/d_esprade.o \
		$(OBJ)/d_feversos.o \
		$(OBJ)/d_gaia.o \
		$(OBJ)/d_guwange.o \
		$(OBJ)/d_sailormn.o \
		$(OBJ)/d_uopoko.o \
		$(OBJ)/d_hotdogst.o \
		$(OBJ)/d_mazinger.o \
		$(OBJ)/d_metmqstr.o \
		$(OBJ)/d_pwrinst2.o \
		$(OBJ)/toaplan.o \
		$(OBJ)/toaplan1.o \
		$(OBJ)/toa_palette.o \
		$(OBJ)/toa_gp9001.o \
		$(OBJ)/toa_extratext.o \
		$(OBJ)/toa_bcu2.o \
		$(OBJ)/d_batrider.o \
		$(OBJ)/d_batsugun.o \
		$(OBJ)/d_battleg.o \
		$(OBJ)/d_bbakraid.o \
		$(OBJ)/d_dogyuun.o \
		$(OBJ)/d_kbash.o \
		$(OBJ)/d_mahoudai.o \
		$(OBJ)/d_outzone.o \
		$(OBJ)/d_shippumd.o \
		$(OBJ)/d_snowbro2.o \
		$(OBJ)/d_tekipaki.o \
		$(OBJ)/d_truxton2.o \
		$(OBJ)/d_vfive.o \
		$(OBJ)/d_truxton.o \
		$(OBJ)/d_hellfire.o \
		$(OBJ)/d_zerowing.o \
		$(OBJ)/unzip.o \
		$(OBJ)/zipfn.o \
		$(OBJ)/bzip.o \
		$(OBJ)/statec.o \
		$(OBJ)/state.o \
		$(OBJ)/drv.o \
		$(OBJ)/run.o \
		$(OBJ)/input.o 

INTERFACES =	
DIST	=	
TARGET	=	fba2x
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) 
	strip $(TARGET)

clean:
	-rm -f $(OBJECTS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

$(OBJ)/gp2xsdk.o: gp2xsdk.cpp gp2xsdk.h
	$(CC) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/gp2xsdk.o gp2xsdk.cpp

$(OBJ)/gles2.o: gles2.cpp
	$(CC) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/gles2.o gles2.cpp

$(OBJ)/thread.o: thread.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/thread.o thread.c

$(OBJ)/fifo_buffer.o: fifo_buffer.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/fifo_buffer.o fifo_buffer.c

$(OBJ)/main.o: main.cpp \
		main.h \
		configfile.h \
		fba_player.h \
		gamewidget.h \
		burner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/main.o main.cpp

$(OBJ)/gamewidget.o: gamewidget.cpp \
		gamewidget.h \
		configfile.h \
		font.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/gamewidget.o gamewidget.cpp

$(OBJ)/ezxaudio.o: ezxaudio.cpp \
		ezxaudio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/ezxaudio.o ezxaudio.cpp

$(OBJ)/fba_player.o: fba_player.cpp \
		fba_player.h \
		gamewidget.h \
		ezxaudio.h \
		font.h \
		snd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/fba_player.o fba_player.cpp

$(OBJ)/font.o: font.cpp \
		font.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/font.o font.cpp

$(OBJ)/snd.o: snd.cpp \
		burner.h \
		snd.h \
		ezxaudio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/snd.o snd.cpp

$(OBJ)/cache.o: cache.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cache.o cache.cpp

$(OBJ)/cz80.o: cpu/cz80/cz80.c
	$(CC) -c $(CFLAGSPROFILE) $(INCPATH) -o $(OBJ)/cz80.o cpu/cz80/cz80.c

$(OBJ)/cyclone.o: cpu/cyclone/cyclone.s
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cyclone.o cpu/cyclone/cyclone.s

$(OBJ)/z80.o: cpu/z80/z80.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/z80.o cpu/z80/z80.cpp

$(OBJ)/z80daisy.o: cpu/z80/z80daisy.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/z80daisy.o cpu/z80/z80daisy.cpp

$(OBJ)/nec.o: cpu/nec/nec.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/nec.o cpu/nec/nec.cpp

$(OBJ)/sh2.o: cpu/sh2/sh2.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/sh2.o cpu/sh2/sh2.cpp

$(OBJ)/ay8910.o: burn/ay8910.c \
		burn/driver.h \
		burn/state.h \
		burn/ay8910.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/ay8910.o burn/ay8910.c

$(OBJ)/burn_ym2151.o: burn/burn_ym2151.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_ym2151.o burn/burn_ym2151.cpp

$(OBJ)/burn_ym2610.o: burn/burn_ym2610.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h \
		burn/burn_ym2610.h \
		burn/driver.h \
		burn/ay8910.h \
		burn/fm.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_ym2610.o burn/burn_ym2610.cpp

$(OBJ)/burn_ym3812.o: burn/burn_ym3812.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h \
		burn/burn_ym3812.h \
		burn/driver.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_ym3812.o burn/burn_ym3812.cpp

$(OBJ)/burn_ym2203.o: burn/burn_ym2203.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_ym2203.o burn/burn_ym2203.cpp

$(OBJ)/burn_ym2608.o: burn/burn_ym2608.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_ym2608.o burn/burn_ym2608.cpp

$(OBJ)/burn_ymf278b.o: burn/burn_ymf278b.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h \
		burn/burn_ymf278b.h \
		burn/driver.h \
		burn/ymf278b.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_ymf278b.o burn/burn_ymf278b.cpp

$(OBJ)/eeprom_93cxx.o: burn/eeprom_93cxx.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/eeprom_93cxx.o burn/eeprom_93cxx.cpp

$(OBJ)/fm.o: burn/fm.c \
		burn/driver.h \
		burn/state.h \
		burn/ay8910.h \
		burn/fm.h \
		burn/ymdeltat.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/fm.o burn/fm.c

$(OBJ)/fmopl.o: burn/fmopl.c \
		burn/driver.h \
		burn/ymdeltat.h \
		burn/fmopl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/fmopl.o burn/fmopl.c

$(OBJ)/msm5205.o: burn/msm5205.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm5205.h \
		burn/burn_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/msm5205.o burn/msm5205.cpp

$(OBJ)/msm6295.o: burn/msm6295.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/msm6295.o burn/msm6295.cpp

$(OBJ)/timer.o: burn/timer.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/timer.o burn/timer.cpp

$(OBJ)/ym2151.o: burn/ym2151.c \
		burn/driver.h \
		burn/state.h \
		burn/ym2151.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/ym2151.o burn/ym2151.c

$(OBJ)/ymdeltat.o: burn/ymdeltat.c \
		burn/driver.h \
		burn/state.h \
		burn/ymdeltat.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/ymdeltat.o burn/ymdeltat.c

$(OBJ)/ymf278b.o: burn/ymf278b.c \
		burn/driver.h \
		burn/ymf278b.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/ymf278b.o burn/ymf278b.c

$(OBJ)/ymz280b.o: burn/ymz280b.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/ymz280b.h \
		burn/burn_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/ymz280b.o burn/ymz280b.cpp

$(OBJ)/burn_sound.o: burn/burn_sound.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_sound.o burn/burn_sound.cpp

$(OBJ)/burn_sound_c.o: burn/burn_sound_c.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn_sound_c.o burn/burn_sound_c.cpp

$(OBJ)/burn.o: burn/burn.cpp \
		burn/version.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_sound.h \
		burn/driverlist.h \
		burn/driver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/burn.o burn/burn.cpp

$(OBJ)/load.o: burn/load.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/load.o burn/load.cpp

$(OBJ)/sek.o: burn/sek.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/sekdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/sek.o burn/sek.cpp

$(OBJ)/czet.o: burn/czet.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/czet.o burn/czet.cpp

$(OBJ)/zet.o: burn/zet.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/zet.o burn/zet.cpp

$(OBJ)/vez.o: burn/vez.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/vez.o burn/vez.cpp

$(OBJ)/cps.o: burn/capcom/cps.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps.o burn/capcom/cps.cpp

$(OBJ)/cps_draw.o: burn/capcom/cps_draw.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_draw.o burn/capcom/cps_draw.cpp

$(OBJ)/cps_mem.o: burn/capcom/cps_mem.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_mem.o burn/capcom/cps_mem.cpp

$(OBJ)/cps2_crpt.o: burn/capcom/cps2_crpt.cpp \
		burn/driver.h \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps2_crpt.o burn/capcom/cps2_crpt.cpp

$(OBJ)/cps_obj.o: burn/capcom/cps_obj.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_obj.o burn/capcom/cps_obj.cpp

$(OBJ)/cps_pal.o: burn/capcom/cps_pal.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_pal.o burn/capcom/cps_pal.cpp

$(OBJ)/cps_run.o: burn/capcom/cps_run.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_run.o burn/capcom/cps_run.cpp

$(OBJ)/cps_rw.o: burn/capcom/cps_rw.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_rw.o burn/capcom/cps_rw.cpp

$(OBJ)/cps_scr.o: burn/capcom/cps_scr.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps_scr.o burn/capcom/cps_scr.cpp

$(OBJ)/cpsr.o: burn/capcom/cpsr.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cpsr.o burn/capcom/cpsr.cpp

$(OBJ)/cpsrd.o: burn/capcom/cpsrd.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cpsrd.o burn/capcom/cpsrd.cpp

$(OBJ)/cpst.o: burn/capcom/cpst.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cpst.o burn/capcom/cpst.cpp

$(OBJ)/ctv.o: burn/capcom/ctv.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h \
		burn/capcom/ctv.h \
		burn/capcom/ctv_do.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/ctv.o burn/capcom/ctv.cpp

$(OBJ)/dc_3wonders.o: burn/capcom/dc_3wonders.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_3wonders.o burn/capcom/dc_3wonders.cpp

$(OBJ)/dc_19xx.o: burn/capcom/dc_19xx.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_19xx.o burn/capcom/dc_19xx.cpp

$(OBJ)/dc_1941.o: burn/capcom/dc_1941.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_1941.o burn/capcom/dc_1941.cpp

$(OBJ)/dc_1944.o: burn/capcom/dc_1944.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_1944.o burn/capcom/dc_1944.cpp

$(OBJ)/dc_armwar.o: burn/capcom/dc_armwar.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_armwar.o burn/capcom/dc_armwar.cpp

$(OBJ)/dc_avsp.o: burn/capcom/dc_avsp.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_avsp.o burn/capcom/dc_avsp.cpp

$(OBJ)/dc_batcir.o: burn/capcom/dc_batcir.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_batcir.o burn/capcom/dc_batcir.cpp

$(OBJ)/dc_captcomm.o: burn/capcom/dc_captcomm.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_captcomm.o burn/capcom/dc_captcomm.cpp

$(OBJ)/dc_cawing.o: burn/capcom/dc_cawing.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_cawing.o burn/capcom/dc_cawing.cpp

$(OBJ)/dc_choko.o: burn/capcom/dc_choko.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_choko.o burn/capcom/dc_choko.cpp

$(OBJ)/dc_csclub.o: burn/capcom/dc_csclub.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_csclub.o burn/capcom/dc_csclub.cpp

$(OBJ)/dc_cworld2j.o: burn/capcom/dc_cworld2j.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_cworld2j.o burn/capcom/dc_cworld2j.cpp

$(OBJ)/dc_cyb.o: burn/capcom/dc_cyb.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_cyb.o burn/capcom/dc_cyb.cpp

$(OBJ)/dc_ddsom.o: burn/capcom/dc_ddsom.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ddsom.o burn/capcom/dc_ddsom.cpp

$(OBJ)/dc_ddtod.o: burn/capcom/dc_ddtod.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ddtod.o burn/capcom/dc_ddtod.cpp

$(OBJ)/dc_dimahoo.o: burn/capcom/dc_dimahoo.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_dimahoo.o burn/capcom/dc_dimahoo.cpp

$(OBJ)/dc_dino.o: burn/capcom/dc_dino.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_dino.o burn/capcom/dc_dino.cpp

$(OBJ)/dc_dstlk.o: burn/capcom/dc_dstlk.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_dstlk.o burn/capcom/dc_dstlk.cpp

$(OBJ)/dc_dw.o: burn/capcom/dc_dw.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_dw.o burn/capcom/dc_dw.cpp

$(OBJ)/dc_ecofghtr.o: burn/capcom/dc_ecofghtr.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ecofghtr.o burn/capcom/dc_ecofghtr.cpp

$(OBJ)/dc_ffight.o: burn/capcom/dc_ffight.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ffight.o burn/capcom/dc_ffight.cpp

$(OBJ)/dc_forgottn.o: burn/capcom/dc_forgottn.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_forgottn.o burn/capcom/dc_forgottn.cpp

$(OBJ)/dc_ghouls.o: burn/capcom/dc_ghouls.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ghouls.o burn/capcom/dc_ghouls.cpp

$(OBJ)/dc_gigawing.o: burn/capcom/dc_gigawing.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_gigawing.o burn/capcom/dc_gigawing.cpp

$(OBJ)/dc_hsf2.o: burn/capcom/dc_hsf2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_hsf2.o burn/capcom/dc_hsf2.cpp

$(OBJ)/dc_input.o: burn/capcom/dc_input.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_input.o burn/capcom/dc_input.cpp

$(OBJ)/dc_jyangoku.o: burn/capcom/dc_jyangoku.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_jyangoku.o burn/capcom/dc_jyangoku.cpp

$(OBJ)/dc_knights.o: burn/capcom/dc_knights.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_knights.o burn/capcom/dc_knights.cpp

$(OBJ)/dc_kod.o: burn/capcom/dc_kod.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_kod.o burn/capcom/dc_kod.cpp

$(OBJ)/dc_megaman2.o: burn/capcom/dc_megaman2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_megaman2.o burn/capcom/dc_megaman2.cpp

$(OBJ)/dc_megaman.o: burn/capcom/dc_megaman.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_megaman.o burn/capcom/dc_megaman.cpp

$(OBJ)/dc_mercs.o: burn/capcom/dc_mercs.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_mercs.o burn/capcom/dc_mercs.cpp

$(OBJ)/dc_mmatrix.o: burn/capcom/dc_mmatrix.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_mmatrix.o burn/capcom/dc_mmatrix.cpp

$(OBJ)/dc_mpang.o: burn/capcom/dc_mpang.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_mpang.o burn/capcom/dc_mpang.cpp

$(OBJ)/dc_msh.o: burn/capcom/dc_msh.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_msh.o burn/capcom/dc_msh.cpp

$(OBJ)/dc_mshvsf.o: burn/capcom/dc_mshvsf.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_mshvsf.o burn/capcom/dc_mshvsf.cpp

$(OBJ)/dc_msword.o: burn/capcom/dc_msword.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_msword.o burn/capcom/dc_msword.cpp

$(OBJ)/dc_mtwins.o: burn/capcom/dc_mtwins.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_mtwins.o burn/capcom/dc_mtwins.cpp

$(OBJ)/dc_mvsc.o: burn/capcom/dc_mvsc.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_mvsc.o burn/capcom/dc_mvsc.cpp

$(OBJ)/dc_nemo.o: burn/capcom/dc_nemo.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_nemo.o burn/capcom/dc_nemo.cpp

$(OBJ)/dc_nwarr.o: burn/capcom/dc_nwarr.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_nwarr.o burn/capcom/dc_nwarr.cpp

$(OBJ)/dc_pang3.o: burn/capcom/dc_pang3.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_pang3.o burn/capcom/dc_pang3.cpp

$(OBJ)/dc_pnickj.o: burn/capcom/dc_pnickj.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_pnickj.o burn/capcom/dc_pnickj.cpp

$(OBJ)/dc_progear.o: burn/capcom/dc_progear.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_progear.o burn/capcom/dc_progear.cpp

$(OBJ)/dc_punisher.o: burn/capcom/dc_punisher.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_punisher.o burn/capcom/dc_punisher.cpp

$(OBJ)/dc_pzloop2.o: burn/capcom/dc_pzloop2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_pzloop2.o burn/capcom/dc_pzloop2.cpp

$(OBJ)/dc_qad.o: burn/capcom/dc_qad.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_qad.o burn/capcom/dc_qad.cpp

$(OBJ)/dc_qnd.o: burn/capcom/dc_qnd.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_qnd.o burn/capcom/dc_qnd.cpp

$(OBJ)/dc_qtono2.o: burn/capcom/dc_qtono2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_qtono2.o burn/capcom/dc_qtono2.cpp


$(OBJ)/dc_ringdest.o: burn/capcom/dc_ringdest.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ringdest.o burn/capcom/dc_ringdest.cpp

$(OBJ)/dc_sf2.o: burn/capcom/dc_sf2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sf2.o burn/capcom/dc_sf2.cpp

$(OBJ)/dc_sf2t.o: burn/capcom/dc_sf2t.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sf2t.o burn/capcom/dc_sf2t.cpp

$(OBJ)/dc_sfa2.o: burn/capcom/dc_sfa2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sfa2.o burn/capcom/dc_sfa2.cpp

$(OBJ)/dc_sfa3.o: burn/capcom/dc_sfa3.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sfa3.o burn/capcom/dc_sfa3.cpp

$(OBJ)/dc_sfa.o: burn/capcom/dc_sfa.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sfa.o burn/capcom/dc_sfa.cpp

$(OBJ)/dc_sfzch.o: burn/capcom/dc_sfzch.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sfzch.o burn/capcom/dc_sfzch.cpp

$(OBJ)/dc_sgemf.o: burn/capcom/dc_sgemf.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_sgemf.o burn/capcom/dc_sgemf.cpp

$(OBJ)/dc_slammast.o: burn/capcom/dc_slammast.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_slammast.o burn/capcom/dc_slammast.cpp

$(OBJ)/dc_spf.o: burn/capcom/dc_spf.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_spf.o burn/capcom/dc_spf.cpp

$(OBJ)/dc_ssf2.o: burn/capcom/dc_ssf2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ssf2.o burn/capcom/dc_ssf2.cpp

$(OBJ)/dc_ssf2t.o: burn/capcom/dc_ssf2t.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_ssf2t.o burn/capcom/dc_ssf2t.cpp

$(OBJ)/dc_strider.o: burn/capcom/dc_strider.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_strider.o burn/capcom/dc_strider.cpp

$(OBJ)/dc_unsquad.o: burn/capcom/dc_unsquad.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_unsquad.o burn/capcom/dc_unsquad.cpp

$(OBJ)/dc_varth.o: burn/capcom/dc_varth.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_varth.o burn/capcom/dc_varth.cpp

$(OBJ)/dc_vhunt2.o: burn/capcom/dc_vhunt2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_vhunt2.o burn/capcom/dc_vhunt2.cpp

$(OBJ)/dc_vsav2.o: burn/capcom/dc_vsav2.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_vsav2.o burn/capcom/dc_vsav2.cpp

$(OBJ)/dc_vsav.o: burn/capcom/dc_vsav.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_vsav.o burn/capcom/dc_vsav.cpp

$(OBJ)/dc_willow.o: burn/capcom/dc_willow.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_willow.o burn/capcom/dc_willow.cpp

$(OBJ)/dc_wof.o: burn/capcom/dc_wof.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_wof.o burn/capcom/dc_wof.cpp

$(OBJ)/dc_xmcota.o: burn/capcom/dc_xmcota.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_xmcota.o burn/capcom/dc_xmcota.cpp

$(OBJ)/dc_xmvsf.o: burn/capcom/dc_xmvsf.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/dc_xmvsf.o burn/capcom/dc_xmvsf.cpp

$(OBJ)/kabuki.o: burn/capcom/kabuki.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/kabuki.o burn/capcom/kabuki.cpp

$(OBJ)/ps.o: burn/capcom/ps.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h \
		burn/driver.h \
		burn/ym2151.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/ps.o burn/capcom/ps.cpp

$(OBJ)/ps_m.o: burn/capcom/ps_m.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/ps_m.o burn/capcom/ps_m.cpp

$(OBJ)/ps_z.o: burn/capcom/ps_z.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/ps_z.o burn/capcom/ps_z.cpp

$(OBJ)/qs.o: burn/capcom/qs.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/qs.o burn/capcom/qs.cpp

$(OBJ)/qs_c.o: burn/capcom/qs_c.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h \
		burn/burn_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/qs_c.o burn/capcom/qs_c.cpp

$(OBJ)/qs_z.o: burn/capcom/qs_z.cpp \
		burn/capcom/cps.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/eeprom_93cxx.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/qs_z.o burn/capcom/qs_z.cpp

$(OBJ)/cps3run.o: burn/cps3/cps3run.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps3run.o burn/cps3/cps3run.cpp

$(OBJ)/cps3snd.o: burn/cps3/cps3snd.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cps3snd.o burn/cps3/cps3snd.cpp

$(OBJ)/d_cps3.o: burn/cps3/d_cps3.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_cps3.o burn/cps3/d_cps3.cpp

$(OBJ)/d_psikyosh.o: burn/cps3/d_psikyosh.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_psikyosh.o burn/cps3/d_psikyosh.cpp

$(OBJ)/d_suprnova.o: burn/cps3/d_suprnova.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_suprnova.o burn/cps3/d_suprnova.cpp

$(OBJ)/neo_decrypt.o: burn/neogeo/neo_decrypt.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neo_decrypt.o burn/neogeo/neo_decrypt.cpp

$(OBJ)/neo_palette.o: burn/neogeo/neo_palette.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neo_palette.o burn/neogeo/neo_palette.cpp

$(OBJ)/neo_run.o: burn/neogeo/neo_run.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_ym2610.h \
		burn/driver.h \
		burn/ay8910.h \
		burn/fm.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neo_run.o burn/neogeo/neo_run.cpp

$(OBJ)/neo_sprite.o: burn/neogeo/neo_sprite.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/neogeo/neo_sprite_func.h \
		burn/neogeo/neo_sprite_render.h \
		burn/neogeo/neo_sprite_func_table.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neo_sprite.o burn/neogeo/neo_sprite.cpp

$(OBJ)/neo_text.o: burn/neogeo/neo_text.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/neogeo/neo_text_render.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neo_text.o burn/neogeo/neo_text.cpp

$(OBJ)/neo_upd4990a.o: burn/neogeo/neo_upd4990a.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neo_upd4990a.o burn/neogeo/neo_upd4990a.cpp

$(OBJ)/neogeo.o: burn/neogeo/neogeo.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/neogeo.o burn/neogeo/neogeo.cpp

$(OBJ)/d_neogeo.o: burn/neogeo/d_neogeo.cpp \
		burn/neogeo/neogeo.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/d_neogeo.o burn/neogeo/d_neogeo.cpp

$(OBJ)/d_parent.o: burn/misc/d_parent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_parent.o burn/misc/d_parent.cpp

$(OBJ)/d_aerofgt.o: burn/misc/d_aerofgt.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/burn_ym2610.h \
		burn/driver.h \
		burn/ay8910.h \
		burn/fm.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_aerofgt.o burn/misc/d_aerofgt.cpp

$(OBJ)/d_galpanic.o: burn/misc/d_galpanic.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/driver.h \
		burn/msm6295.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_galpanic.o burn/misc/d_galpanic.cpp

$(OBJ)/d_wwfwfest.o: burn/misc/d_wwfwfest.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/driver.h \
		burn/msm6295.h
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/d_wwfwfest.o burn/misc/d_wwfwfest.cpp

$(OBJ)/d_gaiden.o: burn/misc/d_gaiden.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_gaiden.o burn/misc/d_gaiden.cpp

$(OBJ)/d_unico.o: burn/misc/d_unico.cpp 
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/d_unico.o burn/misc/d_unico.cpp

$(OBJ)/d_esd16.o: burn/misc/d_esd16.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_esd16.o burn/misc/d_esd16.cpp

$(OBJ)/d_pgm.o: burn/pgm/d_pgm.cpp
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/d_pgm.o burn/pgm/d_pgm.cpp

$(OBJ)/pgm_crypt.o: burn/pgm/pgm_crypt.cpp
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/pgm_crypt.o burn/pgm/pgm_crypt.cpp

$(OBJ)/pgm_draw.o: burn/pgm/pgm_draw.cpp
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/pgm_draw.o burn/pgm/pgm_draw.cpp

$(OBJ)/pgm_prot.o: burn/pgm/pgm_prot.cpp
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/pgm_prot.o burn/pgm/pgm_prot.cpp

$(OBJ)/pgm_snd.o: burn/pgm/pgm_snd.cpp
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/pgm_snd.o burn/pgm/pgm_snd.cpp

$(OBJ)/pgm_run.o: burn/pgm/pgm_run.cpp 
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/pgm_run.o burn/pgm/pgm_run.cpp

$(OBJ)/d_biomtoy.o: burn/misc/d_biomtoy.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_biomtoy.o burn/misc/d_biomtoy.cpp

$(OBJ)/d_bombjack.o: burn/misc/d_bombjack.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_bombjack.o burn/misc/d_bombjack.cpp

$(OBJ)/d_hyperpac.o: burn/misc/d_hyperpac.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_hyperpac.o burn/misc/d_hyperpac.cpp

$(OBJ)/d_kaneko16.o: burn/misc/d_kaneko16.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_kaneko16.o burn/misc/d_kaneko16.cpp

$(OBJ)/d_fstarfrc.o: burn/misc/d_fstarfrc.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_fstarfrc.o burn/misc/d_fstarfrc.cpp

$(OBJ)/d_powerins.o: burn/misc/d_powerins.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_powerins.o burn/misc/d_powerins.cpp

$(OBJ)/d_news.o: burn/misc/d_news.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_news.o burn/misc/d_news.cpp

$(OBJ)/d_ohmygod.o: burn/misc/d_ohmygod.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_ohmygod.o burn/misc/d_ohmygod.cpp

$(OBJ)/d_wc90.o: burn/misc/d_wc90.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_wc90.o burn/misc/d_wc90.cpp

$(OBJ)/d_m92.o: burn/misc/d_m92.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_m92.o burn/misc/d_m92.cpp

$(OBJ)/d_1945kiii.o: burn/misc/d_1945kiii.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_1945kiii.o burn/misc/d_1945kiii.cpp

$(OBJ)/d_tumbleb.o: burn/misc/d_tumbleb.cpp
	$(CXX) -c $(CXXFLAGSPROFILE) $(INCPATH) -o $(OBJ)/d_tumbleb.o burn/misc/d_tumbleb.cpp

$(OBJ)/tiles_generic.o: burn/misc/tiles_generic.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/tiles_generic.o burn/misc/tiles_generic.cpp

$(OBJ)/cave.o: burn/cave/cave.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cave.o burn/cave/cave.cpp

$(OBJ)/cave_palette.o: burn/cave/cave_palette.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cave_palette.o burn/cave/cave_palette.cpp

$(OBJ)/cave_sprite.o: burn/cave/cave_sprite.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/cave/cave_sprite_func.h \
		burn/cave/cave_sprite_render.h \
		burn/cave/cave_sprite_render_zoom.h \
		burn/cave/cave_sprite_func_table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cave_sprite.o burn/cave/cave_sprite.cpp

$(OBJ)/cave_tile.o: burn/cave/cave_tile.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/cave/cave_tile_func.h \
		burn/cave/cave_tile_render.h \
		burn/cave/cave_tile_func_table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/cave_tile.o burn/cave/cave_tile.cpp

$(OBJ)/d_dodonpachi.o: burn/cave/d_dodonpachi.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_dodonpachi.o burn/cave/d_dodonpachi.cpp

$(OBJ)/d_donpachi.o: burn/cave/d_donpachi.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/msm6295.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_donpachi.o burn/cave/d_donpachi.cpp

$(OBJ)/d_esprade.o: burn/cave/d_esprade.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_esprade.o burn/cave/d_esprade.cpp

$(OBJ)/d_feversos.o: burn/cave/d_feversos.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_feversos.o burn/cave/d_feversos.cpp

$(OBJ)/d_gaia.o: burn/cave/d_gaia.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_gaia.o burn/cave/d_gaia.cpp

$(OBJ)/d_guwange.o: burn/cave/d_guwange.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_guwange.o burn/cave/d_guwange.cpp

$(OBJ)/d_sailormn.o: burn/cave/d_sailormn.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_sailormn.o burn/cave/d_sailormn.cpp

$(OBJ)/d_uopoko.o: burn/cave/d_uopoko.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_uopoko.o burn/cave/d_uopoko.cpp

$(OBJ)/d_hotdogst.o: burn/cave/d_hotdogst.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_hotdogst.o burn/cave/d_hotdogst.cpp

$(OBJ)/d_mazinger.o: burn/cave/d_mazinger.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_mazinger.o burn/cave/d_mazinger.cpp

$(OBJ)/d_metmqstr.o: burn/cave/d_metmqstr.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_metmqstr.o burn/cave/d_metmqstr.cpp

$(OBJ)/d_pwrinst2.o: burn/cave/d_pwrinst2.cpp \
		burn/cave/cave.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/eeprom_93cxx.h \
		burn/ymz280b.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_pwrinst2.o burn/cave/d_pwrinst2.cpp

$(OBJ)/toaplan.o: burn/toaplan/toaplan.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/toaplan.o burn/toaplan/toaplan.cpp

$(OBJ)/toaplan1.o: burn/toaplan/toaplan1.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/toaplan1.o burn/toaplan/toaplan1.cpp

$(OBJ)/toa_palette.o: burn/toaplan/toa_palette.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/toa_palette.o burn/toaplan/toa_palette.cpp

$(OBJ)/toa_gp9001.o: burn/toaplan/toa_gp9001.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h \
		burn/toaplan/toa_gp9001_func.h \
		burn/toaplan/toa_gp9001_render.h \
		burn/toaplan/toa_gp9001_func_table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/toa_gp9001.o burn/toaplan/toa_gp9001.cpp

$(OBJ)/toa_extratext.o: burn/toaplan/toa_extratext.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h \
		burn/toaplan/toa_extratext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/toa_extratext.o burn/toaplan/toa_extratext.cpp

$(OBJ)/toa_bcu2.o: burn/toaplan/toa_bcu2.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h \
		burn/toaplan/toa_gp9001_func.h \
		burn/toaplan/toa_gp9001_render.h \
		burn/toaplan/toa_gp9001_func_table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/toa_bcu2.o burn/toaplan/toa_bcu2.cpp

$(OBJ)/d_batrider.o: burn/toaplan/d_batrider.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_batrider.o burn/toaplan/d_batrider.cpp

$(OBJ)/d_batsugun.o: burn/toaplan/d_batsugun.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_batsugun.o burn/toaplan/d_batsugun.cpp

$(OBJ)/d_battleg.o: burn/toaplan/d_battleg.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_battleg.o burn/toaplan/d_battleg.cpp

$(OBJ)/d_bbakraid.o: burn/toaplan/d_bbakraid.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h \
		burn/ymz280b.h \
		burn/eeprom_93cxx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_bbakraid.o burn/toaplan/d_bbakraid.cpp

$(OBJ)/d_dogyuun.o: burn/toaplan/d_dogyuun.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_dogyuun.o burn/toaplan/d_dogyuun.cpp

$(OBJ)/d_kbash.o: burn/toaplan/d_kbash.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_kbash.o burn/toaplan/d_kbash.cpp

$(OBJ)/d_mahoudai.o: burn/toaplan/d_mahoudai.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_mahoudai.o burn/toaplan/d_mahoudai.cpp

$(OBJ)/d_outzone.o: burn/toaplan/d_outzone.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_outzone.o burn/toaplan/d_outzone.cpp

$(OBJ)/d_shippumd.o: burn/toaplan/d_shippumd.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_shippumd.o burn/toaplan/d_shippumd.cpp

$(OBJ)/d_snowbro2.o: burn/toaplan/d_snowbro2.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_snowbro2.o burn/toaplan/d_snowbro2.cpp

$(OBJ)/d_tekipaki.o: burn/toaplan/d_tekipaki.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_tekipaki.o burn/toaplan/d_tekipaki.cpp

$(OBJ)/d_truxton2.o: burn/toaplan/d_truxton2.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_truxton2.o burn/toaplan/d_truxton2.cpp

$(OBJ)/d_vfive.o: burn/toaplan/d_vfive.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_vfive.o burn/toaplan/d_vfive.cpp

$(OBJ)/d_truxton.o: burn/toaplan/d_truxton.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_truxton.o burn/toaplan/d_truxton.cpp

$(OBJ)/d_hellfire.o: burn/toaplan/d_hellfire.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_hellfire.o burn/toaplan/d_hellfire.cpp

$(OBJ)/d_zerowing.o: burn/toaplan/d_zerowing.cpp \
		burn/toaplan/toaplan.h \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h \
		burn/msm6295.h \
		burn/burn_ym2151.h \
		burn/driver.h \
		burn/ym2151.h \
		burn/burn_ym3812.h \
		burn/fmopl.h \
		burn/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/d_zerowing.o burn/toaplan/d_zerowing.cpp

$(OBJ)/unzip.o: unzip.c \
		unzip.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJ)/unzip.o unzip.c

$(OBJ)/zipfn.o: zipfn.cpp \
		burner.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		unzip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/zipfn.o zipfn.cpp

$(OBJ)/bzip.o: bzip.cpp \
		burner.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/bzip.o bzip.cpp

$(OBJ)/statec.o: statec.cpp \
		burn/burnint.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		burn/sek.h \
		burn/zet.h \
		burn/stdfunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/statec.o statec.cpp

$(OBJ)/state.o: state.cpp \
		burner.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/state.o state.cpp

$(OBJ)/drv.o: drv.cpp \
		burner.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/drv.o drv.cpp

$(OBJ)/run.o: run.cpp \
		burner.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h \
		gamewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/run.o run.cpp

$(OBJ)/input.o: input.cpp \
		burner.h \
		burn/tchar.h \
		burn/burn.h \
		burn/cheat.h \
		burn/state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJ)/input.o input.cpp
