// This file was generated by ./gamelist.pl (perl 5.008007)

// Declaration of all drivers
#define DRV extern struct BurnDriver
DRV		BurnDrvCpsRckmanj;
//		BurnDrv4play;			// 4 player  input test cartridge
DRV		BurnDrvGtmra;
DRV		BurnDrvGtmr;
DRV		BurnDrvCps1941j;
DRV		BurnDrvCps1941;
DRV		BurnDrvCps1944j;
DRV		BurnDrvCps1944;
DRV		BurnDrvCps19xxa;
DRV		BurnDrvCps19xxjr1;
DRV		BurnDrvCps19xx;
DRV		BurnDrvCps19xxb;
DRV		BurnDrvCps19xxh;
DRV		BurnDrvCps19xxj;
DRV		BurnDrvbb2020;
DRV		BurnDrvbba2020;
DRV		BurnDrvbbh2020;
DRV		BurnDrv3Countb;
DRV		BurnDrvAerofgt;
DRV		BurnDrvSonicwi2;
DRV		BurnDrvSonicwi3;
DRV		BurnDrvAODK;
DRV		BurnDrvAirGallet;
DRV		BurnDrvCpsAvspa;
DRV		BurnDrvCpsAvsp;
DRV		BurnDrvCpsAvsph;
DRV		BurnDrvCpsAvspj;
DRV		BurnDrvCpsAvspu;
DRV		BurnDrvAlpham2;
DRV		BurnDrvandrodun;
DRV		BurnDrvCpsArea88;
DRV		BurnDrvBatrider;
DRV		BurnDrvBatridrk;
DRV		BurnDrvBatridra;
DRV		BurnDrvCpsArmwara;
DRV		BurnDrvCpsArmwarr1;
DRV		BurnDrvCpsArmwar;
DRV		BurnDrvCpsArmwaru;
DRV		BurnDrvAof2;
DRV		BurnDrvAof2a;
DRV		BurnDrvAof3k;
DRV		BurnDrvAof3;
DRV		BurnDrvAof;
DRV		BurnDrvBonkadv;
DRV		BurnDrvBakatono;
DRV		BurnDrvBakubrkr;
DRV		BurnDrvbangbead;
DRV		BurnDrvBstars2;
DRV		BurnDrvBstars;
DRV		BurnDrvBatsugun;
DRV		BurnDrvBatsugna;
DRV		BurnDrvBatsugunSP;
DRV		BurnDrvBattleBakraid;
DRV		BurnDrvBattleBakraidU;
DRV		BurnDrvCpsBatcira;
DRV		BurnDrvCpsBatcir;
DRV		BurnDrvCpsBatcirj;
DRV		BurnDrvFlipshot;
DRV		BurnDrvBgareghk;
DRV		BurnDrvBgaregga;
DRV		BurnDrvBgaregnv;
DRV		BurnDrvBgaregcn;
DRV		BurnDrvBgaregt2;
DRV		BurnDrvBattleGB;
DRV		BurnDrvBattleG;
DRV		BurnDrvBiomtoy;
DRV		BurnDrvBlazeon;
DRV		BurnDrvBlazStar;
DRV		BurnDrvBattleGA;
DRV		BurnDrvBloodwar;
DRV		BurnDrvBJourney;
DRV		BurnDrvBombjack;
DRV		BurnDrvbombjac2;
DRV		BurnDrvBreakers;
DRV		BurnDrvBreakRev;
DRV		BurnDrvBurningf;
DRV		BurnDrvBurningh;
DRV		BurnDrvCpsDino;
DRV		BurnDrvCpsDinou;
DRV		BurnDrvCpsDinoj;
DRV		BurnDrvCpsCscluba;
DRV		BurnDrvCpsCsclub;
DRV		BurnDrvCpscsclubh;
DRV		BurnDrvCpsCsclubj;
DRV		BurnDrvCpsCworld2j;
DRV		BurnDrvCpsCaptcomu;
DRV		BurnDrvCpsCaptcomm;
DRV		BurnDrvCpsCaptcomj;
DRV		BurnDrvCTomaday;
DRV		BurnDrvCpsCawingr1;
DRV		BurnDrvCpsCawing;
DRV		BurnDrvCpsCawingu;
DRV		BurnDrvMarukodq;
DRV		BurnDrvCpsChikij;
DRV		BurnDrvCpsChoko;
DRV		BurnDrvCookbib2;
DRV		BurnDrvCookbib3;
DRV		BurnDrvCrSword;
DRV		BurnDrvcthd;
DRV		BurnDrvct2k3sp;
DRV		BurnDrvCyberlip;
DRV		BurnDrvCpsCybotsj;
DRV		BurnDrvCpsCybots;
DRV		BurnDrvCpsCybotsu;
DRV		BurnDrvCpsDaimakai;
DRV		BurnDrvDFeveron;
DRV		BurnDrvCpsDstlka;
DRV		BurnDrvCpsDstlk;
DRV		BurnDrvCpsDstlkur1;
DRV		BurnDrvCpsDstlku;
DRV		BurnDrvdiggerma;
DRV		BurnDrvCpsDimahoo;
DRV		BurnDrvDoDonpachi;
DRV		BurnDrvDoDonpachiJ;
DRV		BurnDrvDogyuun;
DRV		BurnDrvDonpachj;
DRV		BurnDrvDonpachi;
DRV		BurnDrvDonpachk;
DRV		BurnDrvDonpachkr;
DRV		BurnDrvDoubledr;
DRV		BurnDrvCpsDdsomjr1;
DRV		BurnDrvCpsDdsomr3;
DRV		BurnDrvCpsDdsomr2;
DRV		BurnDrvCpsDdsomur1;
DRV		BurnDrvCpsDdsomb;
DRV		BurnDrvCpsDdsomr1;
DRV		BurnDrvCpsDdsoma;
DRV		BurnDrvCpsDdsom;
DRV		BurnDrvCpsDdsomj;
DRV		BurnDrvCpsDdsomu;
DRV		BurnDrvCpsDdtoda;
DRV		BurnDrvCpsDdtodr1;
DRV		BurnDrvCpsDdtodjr1;
DRV		BurnDrvCpsDdtodur1;
DRV		BurnDrvCpsDdtodh;
DRV		BurnDrvCpsDdtodj;
DRV		BurnDrvCpsDdtodu;
DRV		BurnDrvCpsDdtod;
DRV		BurnDrvCpsDw;
DRV		BurnDrvCpsEcofghta;
DRV		BurnDrvCpsEcofghtr;
DRV		BurnDrvCpsEcofghtu;
DRV		BurnDrvEightman;
DRV		BurnDrvEsprade;
DRV		BurnDrvEspradeo;
DRV		BurnDrvEspradej;
DRV		BurnDrvExplbrkr;
DRV		BurnDrvFantasia;
DRV 	BurnDrvFantsia2;
DRV 	BurnDrvFntsia2a; 
DRV 	BurnDrvFantsy95;
DRV		BurnDrvFatFury1;
DRV		BurnDrvFatfury2;
DRV		BurnDrvFatfury3;
DRV		BurnDrvFatfursp;
DRV		BurnDrvFatfursa;
DRV		BurnDrvFeverSOS;
DRV		BurnDrvFightfev;
DRV		BurnDrvFightfeva;
DRV		BurnDrvFswords;
DRV		BurnDrvCpsFfightu;
DRV		BurnDrvCpsFfightj1;
DRV		BurnDrvCpsFfightua;
DRV		BurnDrvCpsFfightj;
DRV		BurnDrvCpsFfight;
DRV		BurnDrvFstarfrc;
DRV		BurnDrvFinalttr;
DRV		BurnDrvFbfrenzy;
DRV		BurnDrvCpsForgottn;
DRV		BurnDrvGaia;
DRV		BurnDrvGalaxyfg;
DRV 	BurnDrvGalhustl;
DRV		BurnDrvGinkun;
DRV		BurnDrvGanryu;
DRV		BurnDrvGaroubl;
DRV		BurnDrvGaroup;
DRV		BurnDrvGarou;
DRV		BurnDrvGarouo;
DRV		BurnDrvGpilots;
DRV		BurnDrvghostlop;
DRV		BurnDrvCpsGhoulsu;
DRV		BurnDrvCpsGhouls;
DRV		BurnDrvCpsGwinga;
DRV		BurnDrvCpsGigawing;
DRV		BurnDrvCpsGwingj;
DRV		BurnDrvGoalx3;
DRV		BurnDrvPowerins;
DRV		BurnDrvGtmr2u;
DRV		BurnDrvGtmre;
DRV		BurnDrvGtmrusa;
DRV		BurnDrvCpsGreatMahouDaiJ;
DRV		BurnDrvGrindStormerA;
DRV		BurnDrvGrindStormer;
DRV		BurnDrvGururin;
DRV		BurnDrvGuwange;
DRV		BurnDrvHellfir1;
DRV		BurnDrvHellfire;
DRV		BurnDrvHellfir2;
DRV		BurnDrvHoneydol;
DRV		BurnDrvHyperpac;
DRV		BurnDrvHyperpcb;
DRV		BurnDrvCpsHsf2j;
DRV		BurnDrvCpsHsf2;
DRV		BurnDrvJockeygp;
DRV		BurnDrvCpsJyangoku;
DRV		BurnDrvJanshin;
DRV		BurnDrvKabukiKl;
DRV		BurnDrvKarnovR;
DRV		BurnDrvKog;
DRV		BurnDrvKotm;
DRV		BurnDrvKotmh;
DRV		BurnDrvKotm2;
DRV		BurnDrvKingdmGP;
DRV		BurnDrvKizuna;
DRV		BurnDrvCpsKnights;
DRV		BurnDrvCpsKnightsj;
DRV		BurnDrvCpsKnightsu;
DRV		BurnDrvKBash;
DRV		BurnDrvlans2004;
DRV		BurnDrvLresort;
DRV		BurnDrvLbowling;
DRV		BurnDrvLegendos;
DRV		BurnDrvCpsLostwrld;
DRV		BurnDrvCpsMswordj;
DRV		BurnDrvCpsMsword;
DRV		BurnDrvCpsMswordu;
DRV		BurnDrvCpsMswordr1;
DRV		BurnDrvMgcrsytj;
DRV		BurnDrvMgcrsyto;
DRV		BurnDrvMgcrsytl;
DRV		BurnDrvMagDrop2;
DRV		BurnDrvMagDrop3;
DRV		BurnDrvMagLord;
DRV		BurnDrvMagLordh;
DRV		BurnDrvMahretsu;
DRV		BurnDrvMahouDai;
DRV		BurnDrvCpsMarsMatrixJ;
DRV		BurnDrvCpsMarsMatrix;
DRV		BurnDrvCpsMsha;
DRV		BurnDrvCpsMsh;
DRV		BurnDrvCpsMshjr1;
DRV		BurnDrvCpsMshu;
DRV		BurnDrvCpsMshb;
DRV		BurnDrvCpsMshh;
DRV		BurnDrvCpsMshj;
DRV		BurnDrvCpsMshvsfa1;
DRV		BurnDrvCpsMshvsfa;
DRV		BurnDrvCpsMshvsfb1;
DRV		BurnDrvCpsMshvsf;
DRV		BurnDrvCpsMshvsfh;
DRV		BurnDrvCpsMshvsfj2;
DRV		BurnDrvCpsMshvsfu1;
DRV		BurnDrvCpsMshvsfj1;
DRV		BurnDrvCpsMshvsfj;
DRV		BurnDrvCpsMshvsfb;
DRV		BurnDrvCpsMshvsfu;
DRV		BurnDrvCpsMvscar1;
DRV		BurnDrvCpsMvsc;
DRV		BurnDrvCpsMvscjr1;
DRV		BurnDrvCpsMvsca;
DRV		BurnDrvCpsMvscb;
DRV		BurnDrvCpsMvsch;
DRV		BurnDrvCpsMvscj;
DRV		BurnDrvCpsMvscu;
DRV		BurnDrvCpsMegaman;
DRV		BurnDrvCpsMegamn2a;
DRV		BurnDrvCpsMegaman2;
DRV		BurnDrvCpsMtwins;
DRV		BurnDrvCpsMercs;
DRV		BurnDrvCpsMercsu;
DRV		BurnDrvCpsMercsua;
DRV		BurnDrvMSlug;
DRV		BurnDrvMSlug2;
DRV		BurnDrvmslug3;
DRV		BurnDrvmslug3n;
DRV		BurnDrvmslug4;
DRV		BurnDrvms4plus;
DRV		BurnDrvmslug5;
DRV		BurnDrvms5pcb;
DRV		BurnDrvms5plus;
DRV		BurnDrvmslug3b6;
DRV		BurnDrvMSlugX;
DRV		BurnDrvCpsMPang;
DRV		BurnDrvCpsMPangj;
DRV		BurnDrvGtmr2a;
DRV		BurnDrvGtmr2;
DRV		BurnDrvMinasan;
DRV		BurnDrvMissw96;
DRV		BurnDrvMissmw96;
DRV		BurnDrvMiexchng;
DRV		BurnDrvMoremore;
DRV		BurnDrvMoremorp;
DRV		BurnDrvCpsMbomberj;
DRV		BurnDrvCpsMbombrdj;
DRV		BurnDrvCpsMbombrd;
DRV		BurnDrvMutnat;
DRV		BurnDrvNam1975;
DRV		BurnDrvNaname;			// no comment
DRV		BurnDrvCpsNemoj;
DRV		BurnDrvCpsNemo;
DRV		BurnDrvNeobombe;
DRV		BurnDrvNeodrift;
DRV		BurnDrvNeoGeo;
DRV		BurnDrvNeomrdo;
DRV 	BurnDrvNewfant;
DRV		BurnDrvTurfmast;
DRV		BurnDrvNeocup98;
DRV		BurnDrvNews;
DRV		BurnDrvNewsa;
DRV		BurnDrvCpsNwarr;
DRV		BurnDrvCpsNwarrb;
DRV		BurnDrvCpsNwarrh;
DRV		BurnDrvCpsNwarru;
DRV		BurnDrvNitD;
DRV		BurnDrvNCombat;
DRV		BurnDrvNCombata;
DRV		BurnDrvNCommand;
DRV		BurnDrvNinjaMas;
DRV		BurnDrvOhmygod;
DRV		BurnDrvragnagrd;
DRV		BurnDrvOutZone;
DRV		BurnDrvOutZonea;
DRV		BurnDrvOutZoneb;
DRV		BurnDrvOutZonec;
DRV		BurnDrvOvertop;
DRV		BurnDrvCpsPang3;
DRV		BurnDrvCpsPang3j;
DRV		BurnDrvPanicbom;
DRV		BurnDrvPgoal;
DRV		BurnDrvCpsPnickj;
DRV		BurnDrvpnyaa;
DRV		BurnDrvCpsPfghtj;
DRV		BurnDrvPopbounc;
DRV		BurnDrvPowerina;
DRV		BurnDrvPowerinb;
DRV		BurnDrvPspikes2;
DRV		BurnDrvCpsPgearr1;
DRV		BurnDrvCpsPgear;
DRV		BurnDrvpreisle2;
DRV		BurnDrvSailorMoon;
DRV		BurnDrvSailorMoonB;
DRV		BurnDrvCpsProgeara;
DRV		BurnDrvCpsProgear;
DRV		BurnDrvCpsProgearj;
DRV		BurnDrvPulstar;
DRV		BurnDrvCpsPzloop2j;
DRV		BurnDrvCpsPzloop2;
DRV		BurnDrvPbobblen;
DRV		BurnDrvPbobblna;
DRV		BurnDrvPbobbl2n;
DRV		BurnDrvPuzzledp;
DRV		BurnDrvPuzzldpr;
DRV		BurnDrvFourin1boot;
DRV		BurnDrvUoPoko;
DRV		BurnDrvJoyjoy;
DRV		BurnDrvCpsQadj;
DRV		BurnDrvCpsQad;
DRV		BurnDrvQuizdais;
DRV		BurnDrvQuizkof;
DRV		BurnDrvQuizdai2;
DRV		BurnDrvCpsQndream;
DRV		BurnDrvCpsQtono2;
DRV		BurnDrvrotd;
DRV		BurnDrvrbff2k;
DRV		BurnDrvrbff2;
DRV		BurnDrvrbff2h;
DRV		BurnDrvrbffspec;
DRV		BurnDrvrbff1;
DRV		BurnDrvRidhero;
DRV		BurnDrvRidheroh;
DRV		BurnDrvCpsRingdest;
DRV		BurnDrvRiot;
DRV		BurnDrvRoboarmy;
DRV		BurnDrvroboarma;
DRV		BurnDrvCpsRockmanj;
DRV		BurnDrvCpsRckman2j;
DRV		BurnDrvSamSho2;
DRV		BurnDrvSamSho3;
DRV		BurnDrvSamSho3a;
DRV		BurnDrvSamSho4;
DRV		BurnDrvsamsho5b;
DRV		BurnDrvsamsho5;
DRV		BurnDrvsamsho5h;
DRV		BurnDrvsamsh5sp;
DRV		BurnDrvsamsh5sh;
DRV		BurnDrvsamsh5sn;
DRV		BurnDrvSamSho;
DRV		BurnDrvCpsWofa;
DRV		BurnDrvCpsSlammast;
DRV		BurnDrvCpsSlammasu;
DRV		BurnDrvSavagere;
DRV		BurnDrvSengoku;
DRV		BurnDrvSengokh;
DRV		BurnDrvSengoku2;
DRV		BurnDrvSengoku3;
DRV		BurnDrvCpsMercsj;
DRV		BurnDrvmatrim;
DRV		BurnDrvShippuMD;
DRV		BurnDrvshocktro;
DRV		BurnDrvShocktra;
DRV		BurnDrvshocktr2;
DRV		BurnDrvSnowbroj;
DRV		BurnDrvSnowbros;
DRV		BurnDrvSnowbroa;
DRV		BurnDrvSnowbrob;
DRV		BurnDrvSnowbroc;
DRV		BurnDrvSnowbro2;
DRV		BurnDrvSnowbro3;
DRV		BurnDrvSocbrawl;
DRV		BurnDrvSStriker;
DRV		BurnDrvSStrikrA;
DRV		BurnDrvspinmast;
DRV		BurnDrvStakwin;
DRV		BurnDrvStakwin2;
DRV		BurnDrvCpsSfach;
DRV		BurnDrvCpsSfar3;
DRV		BurnDrvCpsSfar2;
DRV		BurnDrvCpsSfau;
DRV		BurnDrvCpsSfar1;
DRV		BurnDrvCpsSfa;
DRV		BurnDrvCpsSfa2;
DRV		BurnDrvCpsSfa3b;
DRV		BurnDrvCpsSfa3r1;
DRV		BurnDrvCpsSfa3;
DRV		BurnDrvCpsSf2ua;
DRV		BurnDrvCpsSf2eb;
DRV		BurnDrvCpsSf2ja;
DRV		BurnDrvCpsSf2ub;
DRV		BurnDrvCpsSf2ue;
DRV		BurnDrvCpsSf2jc;
DRV		BurnDrvCpsSf2ud;
DRV		BurnDrvCpsSf2uf;
DRV		BurnDrvCpsSf2;
DRV		BurnDrvCpsSf2ui;
DRV		BurnDrvCpsSf2uk;
DRV		BurnDrvCpsSf2j;
DRV		BurnDrvCpsSf2accp2;
DRV		BurnDrvCpsKouryu;
DRV		BurnDrvCpsSf2m2;
DRV		BurnDrvCpsSf2m4;
DRV		BurnDrvCpsSf2m5;
DRV		BurnDrvCpsSf2m6;
DRV		BurnDrvCpsSf2m7;
DRV		BurnDrvCpsSf2rb;
DRV		BurnDrvCpsSf2rb2;
DRV		BurnDrvCpsSf2red;
DRV		BurnDrvCpsSf2v004;
DRV		BurnDrvCpsSf2yyc;
DRV		BurnDrvCpsSf2ce;
DRV		BurnDrvCpsSf2ceua;
DRV		BurnDrvCpsSf2cej;
DRV		BurnDrvCpsSf2ceub;
DRV		BurnDrvCpsSf2ceuc;
DRV		BurnDrvCpsSf2hf;
DRV		BurnDrvCpsSf2t;
DRV		BurnDrvCpsSf2tj;
DRV		BurnDrvCpsSfzjr2;
DRV		BurnDrvCpsSfza;
DRV		BurnDrvCpsSfzh;
DRV		BurnDrvCpsSfzjr1;
DRV		BurnDrvCpsSfzbr1;
DRV		BurnDrvCpsSfzj;
DRV		BurnDrvCpsSfzch;
DRV		BurnDrvCpsSfzb;
DRV		BurnDrvCpsSfz2a;
DRV		BurnDrvCpsSfz2j;
DRV		BurnDrvCpsSfz2n;
DRV		BurnDrvCpsSfz2br1;
DRV		BurnDrvCpsSfz2h;
DRV		BurnDrvCpsSfz2b;
DRV		BurnDrvCpsSfz2aj;
DRV		BurnDrvCpsSfz2ab;
DRV		BurnDrvCpsSfz2ah;
DRV		BurnDrvCpsSfz2aa;
DRV		BurnDrvCpsSfz3jr2;
DRV		BurnDrvCpsSfz3ar1;
DRV		BurnDrvCpsSfz3jr1;
DRV		BurnDrvCpsSfz3a;
DRV		BurnDrvCpsSfz3j;
DRV		BurnDrvStrHoop;
DRV		BurnDrvCpsStrider;
DRV		BurnDrvCpsStridrua;
DRV		BurnDrvCpsStriderj;
DRV		BurnDrvCpsStridrja;
DRV		BurnDrvs1945p;
DRV		BurnDrvSdodgeb;
DRV		BurnDrvCpsSgemfa;
DRV		BurnDrvCpsSgemfh;
DRV		BurnDrvCpsSgemf;
DRV 	BurnDrvSupmodel;
DRV		BurnDrvCpsSmbombr1;
DRV		BurnDrvCpsSmbomb;
DRV		BurnDrvCpsSpf2ta;
DRV		BurnDrvCpsSpf2t;
DRV		BurnDrvCpsSpf2xj;
DRV		BurnDrvSsideki2;
DRV		BurnDrvSsideki3;
DRV		BurnDrvSsideki;
DRV		BurnDrvCpsSsf2jr2;
DRV		BurnDrvCpsSsf2;
DRV		BurnDrvCpsSsf2jr1;
DRV		BurnDrvCpsSsf2u;
DRV		BurnDrvCpsSsf2ar1;
DRV		BurnDrvCpsSsf2a;
DRV		BurnDrvCpsSsf2j;
DRV		BurnDrvCpsSsf2tbr1;
DRV		BurnDrvCpsSsf2tbj;
DRV		BurnDrvCpsSsf2tb;
DRV		BurnDrvCpsSsf2ta;
DRV		BurnDrvCpsSsf2t;
DRV		BurnDrvCpsSsf2tur1;
DRV		BurnDrvCpsSsf2tu;
DRV		BurnDrvCpsSsf2xj;
DRV		BurnDrvsvcpcb;
DRV		BurnDrvsvcpcba;
DRV		BurnDrvsvc;
DRV		BurnDrvsvcboot;
DRV		BurnDrvsvcplus;
DRV		BurnDrvsvcplusa;
DRV		BurnDrvsvcsplus;
DRV		BurnDrvMOSyougi;
DRV		BurnDrvTws96;
DRV		BurnDrvTekiPaki;
DRV		BurnDrvCpsDwj;
DRV		BurnDrvCpsWofj;
DRV		BurnDrvBerlwall;
DRV		BurnDrvBerlwalt;
DRV		BurnDrvIrrmaze;
DRV		BurnDrvCpsKod;
DRV		BurnDrvCpsKodj;
DRV		BurnDrvCpsKodu;
#if defined FBA_DEBUG
DRV		BurnDrvCpsKodb;			// No Sprites [NOT WORKING]
#endif
DRV		BurnDrvKof94;
DRV		BurnDrvKof95;
DRV		BurnDrvKof95a;
DRV		BurnDrvKof96;
DRV		BurnDrvKof96h;
DRV		BurnDrvKof97;
DRV		BurnDrvKof97a;
DRV		BurnDrvKof97p;
DRV		BurnDrvKof98k;
DRV		BurnDrvKof98n;
DRV		BurnDrvKof98;
//		BurnDrvKof98a;			// Alternate version
DRV		BurnDrvkof99e;
DRV		BurnDrvkof99n;
DRV		BurnDrvkof99p;
DRV		BurnDrvkof99;
DRV		BurnDrvkof99a;
DRV		BurnDrvkof10th;
DRV		BurnDrvkf2k5uni;
DRV		BurnDrvkf10thep;
DRV		BurnDrvkof2000;
DRV		BurnDrvkof2000n;
DRV		BurnDrvkof2001;
DRV		BurnDrvkof2001h;
DRV		BurnDrvkof2002;
DRV		BurnDrvkf2k2mp;
DRV		BurnDrvkf2k2mp2;
DRV		BurnDrvkf2k2pls;
DRV		BurnDrvkf2k2pla;
DRV		BurnDrvkf2k3bl;
DRV		BurnDrvkf2k3bla;
DRV		BurnDrvkf2k3pcb;
DRV		BurnDrvkof2003;
DRV		BurnDrvkf2k3pl;
DRV		BurnDrvkf2k3upl;
DRV		BurnDrvkof2k4se;
DRV		BurnDrvlastblad;
DRV		BurnDrvlastbldh;
DRV		BurnDrvlastbld2;
DRV		BurnDrvlastsold;
DRV		BurnDrvCpsPunisher;
DRV		BurnDrvCpsPunishrj;
DRV		BurnDrvCpsPunishru;
DRV		BurnDrvSuperspy;
DRV		BurnDrvSsideki4;
DRV		BurnDrvWintbob;
DRV		BurnDrvTRally;
DRV		BurnDrvCps3wonders;
DRV		BurnDrvCps3wonderu;
DRV		BurnDrvTheroes;
DRV		BurnDrvtophntr;
DRV		BurnDrvtophunta;
DRV		BurnDrvTpgolf;
DRV		BurnDrvToppyrap;
DRV		BurnDrvTruxton2;
DRV		BurnDrvTruxton;
DRV		BurnDrvTwinadvk;
DRV		BurnDrvTwinadv;
DRV		BurnDrvTwinkle;
DRV		BurnDrvTwinSpri;
DRV		BurnDrvCpsUnsquad;
DRV		BurnDrvCpsCawingj;
DRV		BurnDrvCpsUecology;
DRV		BurnDrvUoPokoj;
DRV		BurnDrvVFive;
DRV		BurnDrvVliner;
DRV		BurnDrvVlinero;
DRV		BurnDrvCpsVampjr1;
DRV		BurnDrvCpsVampj;
DRV		BurnDrvCpsVampja;
DRV		BurnDrvCpsVhuntjr2;
DRV		BurnDrvCpsVhuntjr1;
DRV		BurnDrvCpsVhuntj;
DRV		BurnDrvCpsVhunt2r1;
DRV		BurnDrvCpsVhunt2;
DRV		BurnDrvCpsVsava;
DRV		BurnDrvCpsVsav;
DRV		BurnDrvCpsVsavh;
DRV		BurnDrvCpsVsavj;
DRV		BurnDrvCpsVsavu;
DRV		BurnDrvCpsVsav2;
DRV		BurnDrvCpsVarthr1;
DRV		BurnDrvCpsVarthu;
DRV		BurnDrvCpsVarth;
DRV		BurnDrvCpsVarthj;
DRV		BurnDrvViewpoin;
DRV		BurnDrvgowcaizr;
DRV		BurnDrvWakuwak7;
DRV		BurnDrvCpsWof;
DRV		BurnDrvCpsWofu;
DRV		BurnDrvCpsWillowje;
DRV		BurnDrvCpsWillowj;
DRV		BurnDrvCpsWillow;
DRV		BurnDrvWJammers;
DRV		BurnDrvCpsWonder3;
DRV		BurnDrvWc90;
DRV		BurnDrvWc90a;
DRV		BurnDrvWc90t;
DRV		BurnDrvWH1;
DRV		BurnDrvWH1h;
DRV		BurnDrvWH2;
DRV		BurnDrvWH2J;
DRV		BurnDrvWHP;
DRV		BurnDrvCpsXmcotajr;
DRV		BurnDrvCpsXmcotaa;
DRV		BurnDrvCpsXmcotaj1;
DRV		BurnDrvCpsXmcotaj;
DRV		BurnDrvCpsXmcota;
DRV		BurnDrvCpsXmcotau;
DRV		BurnDrvCpsXmcotah;
DRV		BurnDrvCpsXmvsfjr2;
DRV		BurnDrvCpsXmvsfr1;
DRV		BurnDrvCpsXmvsfjr1;
DRV		BurnDrvCpsXmvsfar1;
DRV		BurnDrvCpsXmvsf;
DRV		BurnDrvCpsXmvsfh;
DRV		BurnDrvCpsXmvsfj;
DRV		BurnDrvCpsXmvsfur1;
DRV		BurnDrvCpsXmvsfa;
DRV		BurnDrvCpsXmvsfb;
DRV		BurnDrvCpsXmvsfu;
DRV		BurnDrvThreein1semi;
DRV		BurnDrvZedblade;
DRV		BurnDrvZerowing;
DRV		BurnDrvzintrckb;
DRV		BurnDrvZipzap;
DRV		BurnDrvZupapa;

DRV		BurnDrvKaratblz;
DRV		BurnDrvTurbofrc;
DRV		BurnDrvSpinlbrk;
DRV		BurnDrvSpinlbru;
DRV		BurnDrvSpinlbrj;
	
DRV		BurnDrvGalpanic;

DRV		BurnDrvpgm;
DRV		BurnDrvOrlegend;
DRV		BurnDrvOrlegnde;
DRV		BurnDrvOrlegndc;
DRV		BurnDrvOrld111c;
DRV		BurnDrvOrld105k;
DRV		BurnDrvKov;
DRV		BurnDrvKov115;
DRV		BurnDrvKovj;
DRV		BurnDrvKovplus;
DRV		BurnDrvKovplusa;
DRV 	BurnDrvdrgw2;
DRV 	BurnDrvdrgw2c;
DRV 	BurnDrvkillbld;
DRV 	BurnDrvkillbldt;
DRV 	BurnDrvraf102j;
DRV 	BurnDrvpuzlstar;
DRV		BurnDrvphotoy2k;

DRV		BurnDrv1945kiii;

DRV		BurnDrvHook;

DRV		BurnDrvWwfwfest;
DRV		BurnDrvWwfwfsta;
DRV		BurnDrvWwfwfstb;
DRV		BurnDrvWwfwfstj;

DRV		BurnDrvhotdogst;
DRV		BurnDrvmetmqstr;
DRV		BurnDrvnmaster;
DRV		BurnDrvmazinger;
DRV		BurnDrvpwrinst2;
DRV		BurnDrvpwrins2j;
DRV		BurnDrvplegends;
DRV		BurnDrvplegendj;
DRV		BurnDrvplegendj;

DRV		BurnDrvTumblep;
DRV		BurnDrvTumbleb;
DRV		BurnDrvTumbleb2;
DRV		BurnDrvJumpkids;
DRV		BurnDrvMetlsavr;
DRV		BurnDrvPangpang;
DRV		BurnDrvSuprtrio;
DRV		BurnDrvHtchctch;
DRV		BurnDrvCookbib;
DRV		BurnDrvChokChok;
DRV		BurnDrvWlstar;
DRV		BurnDrvWondl96;
DRV		BurnDrvFancywld;
DRV		BurnDrvSdfight;
DRV		BurnDrvBcstry;
DRV		BurnDrvBcstrya;
DRV		BurnDrvSemibase;
DRV		BurnDrvDquizgo;
DRV		BurnDrvJumppop;
DRV		BurnDrvShadoww;
DRV		BurnDrvShadowwa;
DRV		BurnDrvGaiden;
DRV		BurnDrvRyukendn;
DRV		BurnDrvRyukenda;
DRV		BurnDrvWildfang;
DRV		BurnDrvTknight;
DRV		BurnDrvStratof;
DRV		BurnDrvRaiga;
DRV		BurnDrvDrgnbowl;
DRV		BurnDrvBurglarx;
DRV		BurnDrvMultchmp;
DRV		BurnDrvMultchmk;
DRV		BurnDrvHedpanic;
DRV		BurnDrvHedpanif;
DRV		BurnDrvMchampdx;
DRV		BurnDrvMchampda;
DRV		BurnDrvTangtang;
DRV		BurnDrvSwatpolc;	

#undef DRV

// Structure containing addresses of all drivers
// Needs to be kept sorted (using the full game name as the key) to prevent problems with the gamelist in Kaillera
static struct BurnDriver* pDriver[] = {
//	&BurnDrv4play,				// * 4 player input test [4 player  input test cartridge]
	&BurnDrvGtmra,				// 1000 Miglia: Great 1000 Miles Rally (94/06/13)
	&BurnDrvGtmr,				// 1000 Miglia: Great 1000 Miles Rally (94/07/18)
	&BurnDrvCps1941j,			// 1941 - Counter Attack (Japan)
	&BurnDrvCps1941,			// 1941 - Counter Attack (World)
	&BurnDrvCps1944j,			// 1944 - the loop master (000620 Japan)
	&BurnDrvCps1944,			// 1944 - the loop master (000620 USA)
	&BurnDrvCps19xxa,			// 19XX - the war against destiny (951207 Asia)
	&BurnDrvCps19xxjr1,			// 19XX - the war against destiny (951207 Japan)
	&BurnDrvCps19xx,			// 19XX - the war against destiny (951207 USA)
	&BurnDrvCps19xxb,			// 19XX - the war against destiny (951218 Brazil)
	&BurnDrvCps19xxh,			// 19XX - the war against destiny (951218 Hispanic)
	&BurnDrvCps19xxj,			// 19XX - the war against destiny (951225 Japan)
	&BurnDrvbb2020,				// 2020 Super Baseball (set 1)
	&BurnDrvbba2020,			// 2020 Super Baseball (set 2)
	&BurnDrvbbh2020,			// 2020 Super Baseball (set 3)
	&BurnDrv3Countb,			// 3 Count Bout\0Fire Suplex
	&BurnDrvAerofgt,			// Aero Fighters
	&BurnDrvSonicwi2,			// Aero Fighters 2\0Sonic Wings 2
	&BurnDrvSonicwi3,			// Aero Fighters 3\0Sonic Wings 3
	&BurnDrvAODK,				// Aggressors of Dark Kombat\0Tsuukai GANGAN Koushinkyoku
	&BurnDrvAirGallet,			// Air Gallet
	&BurnDrvCpsAvspa,			// Alien vs Predator (940520 Asia)
	&BurnDrvCpsAvsp,			// Alien vs Predator (940520 Euro)
	&BurnDrvCpsAvsph,			// Alien vs Predator (940520 Hispanic)
	&BurnDrvCpsAvspj,			// Alien vs Predator (940520 Japan)
	&BurnDrvCpsAvspu,			// Alien vs Predator (940520 USA)
	&BurnDrvAlpham2,			// Alpha Mission II\0ASO II - last guardian
	&BurnDrvandrodun,			// Andro Dunos
	&BurnDrvCpsArea88,			// Area 88 (Japan)
	&BurnDrvBatrider,			// Armed police Batrider (Batrider ver. Fri Feb 13 1998, Japan)
	&BurnDrvBatridrk,			// Armed police Batrider (Batrider ver. Fri Feb 13 1998, Korea)
	&BurnDrvBatridra,			// Armed police Batrider (Batrider ver. Mon Dec 22 1997, Japan)
	&BurnDrvCpsArmwara,			// Armored Warriors (940920 Asia)
	&BurnDrvCpsArmwarr1,		// Armored Warriors (941011 Europe)
	&BurnDrvCpsArmwar,			// Armored Warriors (941024 Europe)
	&BurnDrvCpsArmwaru,			// Armored Warriors (941024 USA)
	&BurnDrvAof2,				// Art of Fighting 2 (set 1)\0Ryuuko no Ken 2
	&BurnDrvAof2a,				// Art of Fighting 2 (set 2)\0Ryuuko no Ken 2
	&BurnDrvAof3k,				// Art of Fighting 3 - the path of the warrior (korean release)
	&BurnDrvAof3,				// Art of Fighting 3 - the path of the warrior\0Art of Fighting - ryuuko no ken gaiden
	&BurnDrvAof,				// Art of Fighting\0Ryuuko no Ken
	&BurnDrvBonkadv,			// B.C. Kid / Bonk's Adventure / Kyukyoku!! PC Genjin
	&BurnDrvBakatono,			// Bakatonosama Mahjong Manyuki
	&BurnDrvBakubrkr,			// Bakuretsu Breaker
	&BurnDrvbangbead,			// Bang Bead
	&BurnDrvBstars2,			// Baseball Stars 2
	&BurnDrvBstars,				// Baseball Stars Professional
	&BurnDrvBatsugun,			// Batsugun (set 1)
	&BurnDrvBatsugna,			// Batsugun (set 2)
	&BurnDrvBatsugunSP,			// Batsugun Special Ver.
	&BurnDrvBattleBakraid,		// Battle Bakraid (ver. Wed Apr 7 1999)
	&BurnDrvBattleBakraidU,		// Battle Bakraid - Unlimited Version (ver. Tue Jun 8 1999)
	&BurnDrvCpsBatcira,			// Battle Circuit (970319 Asia)
	&BurnDrvCpsBatcir,			// Battle Circuit (970319 Euro)
	&BurnDrvCpsBatcirj,			// Battle Circuit (970319 Japan)
	&BurnDrvFlipshot,			// Battle Flip Shot
	&BurnDrvBgareghk,			// Battle Garegga (Austria / Hong Kong) (Sat Feb 3 1996)
	&BurnDrvBgaregga,			// Battle Garegga (Europe / USA / Japan / Asia) (Sat Feb 3 1996)
	&BurnDrvBgaregnv,			// Battle Garegga - New Version (Austria / Hong Kong) (Sat Mar 2 1996)
	&BurnDrvBgaregcn,			// Battle Garegga - Type 2 (Denmark / China) (Tue Apr 2 1996)
	&BurnDrvBgaregt2,			// Battle Garegga - Type 2 (Europe / USA / Japan / Asia) (Sat Mar 2 1996)
	&BurnDrvBiomtoy,			// Biomechanical Toy (unprotected)
	&BurnDrvBlazeon,			// Blaze On (Japan)
	&BurnDrvBlazStar,			// Blazing Star
	&BurnDrvBloodwar,			// Blood Warrior
	&BurnDrvBJourney,			// Blue's Journey\0Raguy
	&BurnDrvBombjack,			// Bomb Jack (set 1)
	&BurnDrvbombjac2,			// Bomb Jack (set 2)
	&BurnDrvBreakers,			// Breakers
	&BurnDrvBreakRev,			// Breakers Revenge
	&BurnDrvBurningf,			// Burning Fight (set 1)
	&BurnDrvBurningh,			// Burning Fight (set 2)
	&BurnDrvCpsDino,			// Cadillacs & Dinosaurs (930201 etc)
	&BurnDrvCpsDinou,			// Cadillacs & Dinosaurs (930201 USA)
	&BurnDrvCpsDinoj,			// Cadillacs Kyouryuu-Shinseiki (Cadillacs 930201 Japan)
	&BurnDrvCpsCscluba,			// Capcom Sports Club (970722 Asia)
	&BurnDrvCpsCsclub,			// Capcom Sports Club (970722 Euro)
	&BurnDrvCpscsclubh,			// Capcom Sports Club (970722 Hispanic)
	&BurnDrvCpsCsclubj,			// Capcom Sports Club (970722 Japan)
	&BurnDrvCpsCworld2j,		// Capcom World 2 (920611 Japan)
	&BurnDrvCpsCaptcomu,		// Captain Commando (910928 USA)
	&BurnDrvCpsCaptcomm,		// Captain Commando (911014 other country)
	&BurnDrvCpsCaptcomj,		// Captain Commando (911202 Japan)
	&BurnDrvCTomaday,			// Captain Tomaday
	&BurnDrvCpsCawingr1,		// Carrier Air Wing (U.S. navy 901009 etc)
	&BurnDrvCpsCawing,			// Carrier Air Wing (U.S. navy 901012 etc)
	&BurnDrvCpsCawingu,			// Carrier Air Wing (U.S. navy 901012 USA)
	&BurnDrvMarukodq,			// Chibi Marukochan Deluxe Quiz
	&BurnDrvCpsChikij,			// Chiki Chiki Boys (900619 Japan)
	&BurnDrvCpsChoko,			// Choko (010820 Japan)
	&BurnDrvCookbib2,			// Cookie & Bibi 2
	&BurnDrvCookbib3,			// Cookie & Bibi 3
	&BurnDrvCrSword,			// Crossed Swords
	&BurnDrvcthd,				// Crouching Tiger Hidden Dragon 2003 (bootleg)
	&BurnDrvct2k3sp,			// Crouching Tiger Hidden Dragon 2003 Super Plus (bootleg)
	&BurnDrvCyberlip,			// Cyber-Lip
	&BurnDrvCpsCybotsj,			// Cyberbots - fullmetal madness (950420 Japan)
	&BurnDrvCpsCybots,			// Cyberbots - fullmetal madness (950424 Euro)
	&BurnDrvCpsCybotsu,			// Cyberbots - fullmetal madness (950424 USA)
	&BurnDrvCpsDaimakai,		// Dai Makai-Mura (Japan)
	&BurnDrvDFeveron,			// Dangun Feveron (Japan ver. Thu Sep 17 1998)
	&BurnDrvCpsDstlka,			// Darkstalkers - the night warriors (940705 Asia)
	&BurnDrvCpsDstlk,			// Darkstalkers - the night warriors (940705 Euro)
	&BurnDrvCpsDstlkur1,		// Darkstalkers - the night warriors (940705 USA)
	&BurnDrvCpsDstlku,			// Darkstalkers - the night warriors (940818 USA)
	&BurnDrvdiggerma,			// Digger Man
	&BurnDrvCpsDimahoo,			// Dimahoo (000121 USA)
	&BurnDrvDoDonpachi,			// DoDonPachi (1997 2/5 master ver, international)
	&BurnDrvDoDonpachiJ,		// DoDonPachi (1997 2/5 master ver, Japan)
	&BurnDrvDogyuun,			// Dogyuun
	&BurnDrvDonpachj,			// DonPachi (ver. 1.01 1995/05/11, Japan)
	&BurnDrvDonpachi,			// DonPachi (ver. 1.01 1995/05/11, U.S.A)
	&BurnDrvDonpachk,			// DonPachi (ver. 1.12 1995/05/2x, Hong Kong)
	&BurnDrvDonpachkr,			// DonPachi (ver. 1.12 1995/05/2x, Korea)
	&BurnDrvDoubledr,			// Double Dragon
	&BurnDrvCpsDdsomjr1,		// Dungeons & Dragons - shadow over mystara (960206 Japan)
	&BurnDrvCpsDdsomr3,			// Dungeons & Dragons - shadow over mystara (960208 Euro)
	&BurnDrvCpsDdsomr2,			// Dungeons & Dragons - shadow over mystara (960209 Euro)
	&BurnDrvCpsDdsomur1,		// Dungeons & Dragons - shadow over mystara (960209 USA)
	&BurnDrvCpsDdsomb,			// Dungeons & Dragons - shadow over mystara (960223 Brazil)
	&BurnDrvCpsDdsomr1,			// Dungeons & Dragons - shadow over mystara (960223 Euro)
	&BurnDrvCpsDdsoma,			// Dungeons & Dragons - shadow over mystara (960619 Asia)
	&BurnDrvCpsDdsom,			// Dungeons & Dragons - shadow over mystara (960619 Euro)
	&BurnDrvCpsDdsomj,			// Dungeons & Dragons - shadow over mystara (960619 Japan)
	&BurnDrvCpsDdsomu,			// Dungeons & Dragons - shadow over mystara (960619 USA)
	&BurnDrvCpsDdtoda,			// Dungeons & Dragons - tower of doom (940113 Asia)
	&BurnDrvCpsDdtodr1,			// Dungeons & Dragons - tower of doom (940113 Euro)
	&BurnDrvCpsDdtodjr1,		// Dungeons & Dragons - tower of doom (940113 Japan)
	&BurnDrvCpsDdtodur1,		// Dungeons & Dragons - tower of doom (940113 USA)
	&BurnDrvCpsDdtodh,			// Dungeons & Dragons - tower of doom (940125 Hispanic)
	&BurnDrvCpsDdtodj,			// Dungeons & Dragons - tower of doom (940125 Japan)
	&BurnDrvCpsDdtodu,			// Dungeons & Dragons - tower of doom (940125 USA)
	&BurnDrvCpsDdtod,			// Dungeons & Dragons - tower of doom (940412 Euro)
	&BurnDrvCpsDw,				// Dynasty Wars (World)
	&BurnDrvCpsEcofghta,		// Eco Fighters (931203 Asia)
	&BurnDrvCpsEcofghtr,		// Eco Fighters (931203 etc)
	&BurnDrvCpsEcofghtu,		// Eco Fighters (931203 USA)
	&BurnDrvEightman,			// Eight Man
	&BurnDrvEsprade,			// ESP Ra.De. (1998 4/22 international ver.)
	&BurnDrvEspradeo,			// ESP Ra.De. (Japan, 1998 4/14 master ver.)
	&BurnDrvEspradej,			// ESP Ra.De. (Japan, 1998 4/21 master ver.)
	&BurnDrvExplbrkr,			// Explosive Breaker
	&BurnDrvFantasia,			// Fantasia
	&BurnDrvFantsia2,			// Fantasia II (Explicit)
	&BurnDrvFntsia2a,			// Fantasia II (Less Explicit)
	&BurnDrvFantsy95,			// Fantasy '95
	&BurnDrvFatFury1,			// Fatal Fury - king of fighters\0Garou Denetsu - shukumei no tatakai
	&BurnDrvFatfury2,			// Fatal Fury 2\0Garou Densetsu 2 - arata-naru tatakai
	&BurnDrvFatfury3,			// Fatal Fury 3 - road to the final victory\0Garou Densetsu 3
	&BurnDrvFatfursp,			// Fatal Fury Special (set 1)\0Garou Densetsu Special
	&BurnDrvFatfursa,			// Fatal Fury Special (set 2)\0Garou Densetsu Special
	&BurnDrvFeverSOS,			// Fever SOS (International ver. Fri Sep 25 1998)
	&BurnDrvFightfev,			// Fight Fever (set 1)\0Wang Jung Wang
	&BurnDrvFightfeva,			// Fight Fever (set 2)\0Wang Jung Wang
	&BurnDrvFswords,			// Fighters Swords (bootleg)
	&BurnDrvCpsFfightu,			// Final Fight (900112 USA)
	&BurnDrvCpsFfightj1,		// Final Fight (900305 Japan)
	&BurnDrvCpsFfightua,		// Final Fight (900613 USA)
	&BurnDrvCpsFfightj,			// Final Fight (Japan)
	&BurnDrvCpsFfight,			// Final Fight (World)
	&BurnDrvFstarfrc,			// Final Star Force (US)
	&BurnDrvFinalttr,			// Final Tetris
	&BurnDrvFbfrenzy,			// Football Frenzy
	&BurnDrvCpsForgottn,		// Forgotten Worlds (US)
	&BurnDrvGaia,				// Gaia Crusaders
	&BurnDrvGalaxyfg,			// Galaxy Fight - universal warriors
	&BurnDrvGalhustl,			// Gals Hustler
	&BurnDrvGinkun,				// Ganbare Ginkun
	&BurnDrvGanryu,				// Ganryu\0Musashi Ganryuki
	&BurnDrvGaroubl,			// Garou - mark of the wolves (bootleg)
	&BurnDrvGaroup,				// Garou - mark of the wolves (prototype)
	&BurnDrvGarou,				// Garou - mark of the wolves (set 1)
	&BurnDrvGarouo,				// Garou - mark of the wolves (set 2)
	&BurnDrvGpilots,			// Ghost Pilots
	&BurnDrvghostlop,			// Ghostlop
	&BurnDrvCpsGhoulsu,			// Ghouls'n Ghosts (US)
	&BurnDrvCpsGhouls,			// Ghouls'n Ghosts (World)
	&BurnDrvCpsGwinga,			// Giga Wing (990222 Asia)
	&BurnDrvCpsGigawing,		// Giga Wing (990222 USA)
	&BurnDrvCpsGwingj,			// Giga Wing (990223 Japan)
	&BurnDrvGoalx3,				// Goal! Goal! Goal!
	&BurnDrvPowerins,			// Gouketsuji Ichizoku (Japan)
	&BurnDrvGtmr2u,				// Great 1000 Miles Rally 2 USA (95/05/18)
	&BurnDrvGtmre,				// Great 1000 Miles Rally: Evolution Model!!! (94/09/06)
	&BurnDrvGtmrusa,			// Great 1000 Miles Rally: U.S.A Version! (94/09/06)
	&BurnDrvCpsGreatMahouDaiJ,	// Great Mahou Daisakusen (000121 Japan)
	&BurnDrvGrindStormerA,		// Grind Stormer (older set)
	&BurnDrvGrindStormer,		// Grind Stormer
	&BurnDrvGururin,			// Gururin
	&BurnDrvGuwange,			// Guwange (Japan, 1999 6/24 master ver.)
	&BurnDrvHellfir1,			// Hellfire (1P Ver.)
	&BurnDrvHellfire,			// Hellfire (2P Ver.)
	&BurnDrvHellfir2,			// Hellfire (2P Ver., first edition)
	&BurnDrvHoneydol,			// Honey Dolls
	&BurnDrvHyperpac,			// Hyper Pacman
	&BurnDrvHyperpcb,			// Hyper Pacman (bootleg)
	&BurnDrvCpsHsf2j,			// Hyper Street Fighter 2: The Anniversary Edition (031222 Japan)
	&BurnDrvCpsHsf2,			// Hyper Street Fighter 2: The Anniversary Edition (040202 Asia)
	&BurnDrvJockeygp,			// Jockey Grand Prix
	&BurnDrvCpsJyangoku,		// Jyangokushi  -Haoh no Saihai- (990527 Japan)
	&BurnDrvJanshin,			// Jyanshin Densetsu - quest of jongmaster
	&BurnDrvKabukiKl,			// Kabuki Klash - far east of eden\0tengai makyou - Shinden
	&BurnDrvKarnovR,			// Karnov's Revenge\0Fighter's History Dynamite
	&BurnDrvKog,				// King of Gladiator (bootleg)
	&BurnDrvKotm,				// King of the Monsters (set 1)
	&BurnDrvKotmh,				// King of the Monsters (set 2)
	&BurnDrvKotm2,				// King of the Monsters 2 - the next thing
	&BurnDrvKingdmGP,			// Kingdom Grandprix (World)
	&BurnDrvKizuna,				// Kizuna Encounter - super tag battle\0Fu'un Super Tag Battle
	&BurnDrvCpsKnights,			// Knights of the Round (911127 etc)
	&BurnDrvCpsKnightsj,		// Knights of the Round (911127 Japan)
	&BurnDrvCpsKnightsu,		// Knights of the Round (911127 USA)
	&BurnDrvKBash,				// Knuckle Bash
	&BurnDrvlans2004,			// Lansquenet 2004 (bootleg)
	&BurnDrvLresort,			// Last Resort
	&BurnDrvLbowling,			// League Bowling
	&BurnDrvLegendos,			// Legend of Success Joe\0Ashitano Joe Densetsu
	&BurnDrvCpsLostwrld,		// Lost Worlds (Japan)
	&BurnDrvCpsMswordj,			// Magic Sword (23.06.1990 Japan)
	&BurnDrvCpsMsword,			// Magic Sword - heroic fantasy (25.07.1990 other country)
	&BurnDrvCpsMswordu,			// Magic Sword - heroic fantasy (25.07.1990 USA)
	&BurnDrvCpsMswordr1,		// Magic Sword - heroic fantasy (90.06.23 other country)
	&BurnDrvMgcrsytj,			// Magical Crystals (Japan, 92/01/13)
	&BurnDrvMgcrsyto,			// Magical Crystals (World, 91/12/10)
	&BurnDrvMgcrsytl,			// Magical Crystals (World, 92/01/10)
	&BurnDrvMagDrop2,			// Magical Drop II
	&BurnDrvMagDrop3,			// Magical Drop III
	&BurnDrvMagLord,			// Magician Lord (set 1)
	&BurnDrvMagLordh,			// Magician Lord (set 2)
	&BurnDrvMahretsu,			// Mahjong Kyoretsuden - real mah-jong game
	&BurnDrvMahouDai,			// Mahou Daisakusen (Japan)
	&BurnDrvCpsMarsMatrixJ,		// Mars Matrix (000412 Japan)
	&BurnDrvCpsMarsMatrix,		// Mars Matrix (000412 USA)
	&BurnDrvCpsMsha,			// Marvel Super Heroes (951024 Asia)
	&BurnDrvCpsMsh,				// Marvel Super Heroes (951024 Euro)
	&BurnDrvCpsMshjr1,			// Marvel Super Heroes (951024 Japan)
	&BurnDrvCpsMshu,			// Marvel Super Heroes (951024 USA)
	&BurnDrvCpsMshb,			// Marvel Super Heroes (951117 Brazil)
	&BurnDrvCpsMshh,			// Marvel Super Heroes (951117 Hispanic)
	&BurnDrvCpsMshj,			// Marvel Super Heroes (951117 Japan)
	&BurnDrvCpsMshvsfa1,		// Marvel Super Heroes vs Street Fighter (970620 Asia)
	&BurnDrvCpsMshvsfa,			// Marvel Super Heroes vs Street Fighter (970625 Asia)
	&BurnDrvCpsMshvsfb1,		// Marvel Super Heroes vs Street Fighter (970625 Brazil)
	&BurnDrvCpsMshvsf,			// Marvel Super Heroes vs Street Fighter (970625 Euro)
	&BurnDrvCpsMshvsfh,			// Marvel Super Heroes vs Street Fighter (970625 Hispanic)
	&BurnDrvCpsMshvsfj2,		// Marvel Super Heroes vs Street Fighter (970625 Japan)
	&BurnDrvCpsMshvsfu1,		// Marvel Super Heroes vs Street Fighter (970625 USA)
	&BurnDrvCpsMshvsfj1,		// Marvel Super Heroes vs Street Fighter (970702 Japan)
	&BurnDrvCpsMshvsfj,			// Marvel Super Heroes vs Street Fighter (970707 Japan)
	&BurnDrvCpsMshvsfb,			// Marvel Super Heroes vs Street Fighter (970827 Brazil)
	&BurnDrvCpsMshvsfu,			// Marvel Super Heroes vs Street Fighter (970827 USA)
	&BurnDrvCpsMvscar1,			// Marvel vs Capcom - clash of super heroes (980112 Asia)
	&BurnDrvCpsMvsc,			// Marvel vs Capcom - clash of super heroes (980112 Euro)
	&BurnDrvCpsMvscjr1,			// Marvel vs Capcom - clash of super heroes (980112 Japan)
	&BurnDrvCpsMvsca,			// Marvel vs Capcom - clash of super heroes (980123 Asia)
	&BurnDrvCpsMvscb,			// Marvel vs Capcom - clash of super heroes (980123 Brazil)
	&BurnDrvCpsMvsch,			// Marvel vs Capcom - clash of super heroes (980123 Hispanic)
	&BurnDrvCpsMvscj,			// Marvel vs Capcom - clash of super heroes (980123 Japan)
	&BurnDrvCpsMvscu,			// Marvel vs Capcom - clash of super heroes (980123 USA)
	&BurnDrvCpsMegaman,			// Mega Man - the power battle (951006 Asia)
	&BurnDrvCpsMegamn2a,		// Mega Man 2 - the power fighters (960708 Asia)
	&BurnDrvCpsMegaman2,		// Mega Man 2 - the power fighters (960708 USA)
	&BurnDrvCpsMtwins,			// Mega Twins (chiki chiki boys 900619 etc)
	&BurnDrvCpsMercs,			// Mercs (900302 etc)
	&BurnDrvCpsMercsu,			// Mercs (900302 USA)
	&BurnDrvCpsMercsua,			// Mercs (900608 USA)
	&BurnDrvMSlug,				// Metal Slug - super vehicle-001
	&BurnDrvMSlug2,				// Metal Slug 2 - super vehicle-001/II
	&BurnDrvmslug3,				// Metal Slug 3
	&BurnDrvmslug3n,			// Metal Slug 3 (not encrypted)
	&BurnDrvmslug4,				// Metal Slug 4
	&BurnDrvms4plus,			// Metal Slug 4 Plus (bootleg)
	&BurnDrvmslug5,				// Metal Slug 5
	&BurnDrvms5pcb,				// Metal Slug 5 (JAMMA PCB)
	&BurnDrvms5plus,			// Metal Slug 5 Plus (bootleg)
	&BurnDrvmslug3b6,			// Metal Slug 6
	&BurnDrvMSlugX,				// Metal Slug X - super vehicle-001
	&BurnDrvCpsMPang,			// Mighty! Pang (001010 USA)
	&BurnDrvCpsMPangj,			// Mighty! Pang (001011 Japan)
	&BurnDrvGtmr2a,				// Mille Miglia 2: Great 1000 Miles Rally (95/04/04)
	&BurnDrvGtmr2,				// Mille Miglia 2: Great 1000 Miles Rally (95/05/24)
	&BurnDrvMinasan,			// Minnasanno Okagesamadesu
	&BurnDrvMissw96,			// Miss World '96 (Nude)
	&BurnDrvMissmw96,			// Miss Mister World '96 (Nude)
	&BurnDrvMiexchng,			// Money Puzzle Exchanger\0Money Idol Exchanger
	&BurnDrvMoremore,			// More More
	&BurnDrvMoremorp,			// More More Plus
	&BurnDrvCpsMbomberj,		// Muscle Bomber - the body explosion (930713 Japan)
	&BurnDrvCpsMbombrdj,		// Muscle Bomber Duo - heat up warriors (931206 Japan)
	&BurnDrvCpsMbombrd,			// Muscle Bomber Duo - ultimate team battle (931206 etc)
	&BurnDrvMutnat,				// Mutation Nation
	&BurnDrvNam1975,			// NAM - 1975
	&BurnDrvNaname,				// Naname de Magic! [no comment]
	&BurnDrvCpsNemoj,			// Nemo (90 11 20 Japan)
	&BurnDrvCpsNemo,			// Nemo (90 11 30 etc)
	&BurnDrvNeobombe,			// Neo Bomberman
	&BurnDrvNeodrift,			// Neo Drift Out - new technology
	&BurnDrvNeoGeo,				// Neo Geo [BIOS only, NOT WORKING]
	&BurnDrvNeomrdo,			// Neo Mr. Do!
	&BurnDrvNewfant,			// New Fantasia
	&BurnDrvTurfmast,			// Neo Turf Masters\0Big Tournament Golf
	&BurnDrvNeocup98,			// Neo-Geo Cup '98 - the road to the victory
	&BurnDrvNews,				// News (set 1)
	&BurnDrvNewsa,				// News (set 2)
	&BurnDrvCpsNwarr,			// Night Warriors - darkstalkers' revenge (950316 Euro)
	&BurnDrvCpsNwarrb,			// Night Warriors - darkstalkers' revenge (950403 Brazil)
	&BurnDrvCpsNwarrh,			// Night Warriors - darkstalkers' revenge (950403 Hispanic)
	&BurnDrvCpsNwarru,			// Night Warriors - darkstalkers' revenge (950406 USA)
	&BurnDrvNitD,				// Nightmare in the Dark
	&BurnDrvNCombat,			// Ninja Combat (set 1)
	&BurnDrvNCombata,			// Ninja Combat (set 2)
	&BurnDrvNCommand,			// Ninja Commando
	&BurnDrvNinjaMas,			// Ninja Master's haoh ninpo cho
	&BurnDrvOhmygod,			// Oh My God!
	&BurnDrvragnagrd,			// Operation Ragnagard\0Shin-Oh-Ken
	&BurnDrvOutZone,			// Out Zone (set 1)
	&BurnDrvOutZonea,			// Out Zone (set 2)
	&BurnDrvOutZoneb,			// Out Zone (set 3, prototype?)
	&BurnDrvOutZonec,			// Out Zone (set 4)
	&BurnDrvOvertop,			// OverTop
	&BurnDrvCpsPang3,			// Pang! 3 (950511 Euro)
	&BurnDrvCpsPang3j,			// Pang! 3 (950511 Japan)
	&BurnDrvPanicbom,			// Panic Bomber
	&BurnDrvPgoal,				// Pleasure Goal - 5 on 5 mini soccer\0Futsal
	&BurnDrvCpsPnickj,			// Pnickies (940608 Japan)
	&BurnDrvpnyaa,				// Pochi and Nyaa
	&BurnDrvCpsPfghtj,			// Pocket Fighter (970904 Japan)
	&BurnDrvPopbounc,			// Pop 'n Bounce\0Gapporin
	&BurnDrvPowerina,			// Power Instinct (USA, bootleg set 1)
	&BurnDrvPowerinb,			// Power Instinct (USA, bootleg set 2)
	&BurnDrvPspikes2,			// Power Spikes II
	&BurnDrvCpsPgearr1,			// Powered Gear - strategic variant armor equipment (940916 Japan)
	&BurnDrvCpsPgear,			// Powered Gear - strategic variant armor equipment (941024 Japan)
	&BurnDrvpreisle2,			// Prehistoric Isle 2
	&BurnDrvSailorMoon,			// Pretty Soldier Sailor Moon (version 95/03/22)
	&BurnDrvSailorMoonB,		// Pretty Soldier Sailor Moon (version 95/03/22B)
	&BurnDrvCpsProgeara,		// Progear (010117 Asia)
	&BurnDrvCpsProgear,			// Progear (010117 USA)
	&BurnDrvCpsProgearj,		// Progear No Arashi (010117 Japan)
	&BurnDrvPulstar,			// Pulstar
	&BurnDrvCpsPzloop2j,		// Puzz Loop 2 (010205 Japan)
	&BurnDrvCpsPzloop2,			// Puzz Loop 2 (010302 Euro)
	&BurnDrvPbobblen,			// Puzzle Bobble (set 1)\0Bust-A-Move
	&BurnDrvPbobblna,			// Puzzle Bobble (set 2)\0Bust-A-Move
	&BurnDrvPbobbl2n,			// Puzzle Bobble 2\0Bust-A-Move Again
	&BurnDrvPuzzledp,			// Puzzle De Pon
	&BurnDrvPuzzldpr,			// Puzzle De Pon R
	&BurnDrvFourin1boot,		// Puzzle King
	&BurnDrvUoPoko,				// Puzzle Uo Poko (International)
	&BurnDrvJoyjoy,				// Puzzled\0Joy Joy Kid
	&BurnDrvCpsQadj,			// Quiz & Dragons (940921 Japan)
	&BurnDrvCpsQad,				// Quiz & Dragons (capcom quiz game 920701 USA)
	&BurnDrvQuizdais,			// Quiz Daisousa Sen - the last count down
	&BurnDrvQuizkof,			// Quiz King of Fighters
	&BurnDrvQuizdai2,			// Quiz Meintantei Neo Geo - quiz daisousa sen part 2
	&BurnDrvCpsQndream,			// Quiz Nanairo Dreams - nijiirochou no kiseki (nanairo dreams 960826 Japan)
	&BurnDrvCpsQtono2,			// Quiz Tonosama no Yabou 2 Zenkoku-ban (tonosama 2 950123 Japan)
	&BurnDrvrotd,				// Rage of the Dragons
	&BurnDrvrbff2k,				// Real Bout Fatal Fury 2 - the newcomers (Korean Release)\0Real Bout Garou Densetsu - the newcomers
	&BurnDrvrbff2,				// Real Bout Fatal Fury 2 - the newcomers (set 1)\0Real Bout Garou Densetsu - the newcomers
	&BurnDrvrbff2h,				// Real Bout Fatal Fury 2 - the newcomers (set 2)\0Real Bout Garou Densetsu - the newcomers
	&BurnDrvrbffspec,			// Real Bout Fatal Fury Special\0Real Bout Special
	&BurnDrvrbff1,				// Real Bout Fatal Fury\0Real Bout Garou Densetsu
	&BurnDrvRidhero,			// Riding Hero (set 1)
	&BurnDrvRidheroh,			// Riding Hero (set 2)
	&BurnDrvCpsRingdest,		// Ring of Destruction - slammasters II (940902 Euro)
	&BurnDrvRiot,				// Riot
	&BurnDrvRoboarmy,			// Robo Army (set 1)
	&BurnDrvroboarma,			// Robo Army (set 2)
	&BurnDrvCpsRockmanj,		// Rockman - the power battle (950922 Japan)
	&BurnDrvCpsRckman2j,		// Rockman 2 - the power fighters (960708 Japan)
	&BurnDrvSamSho2,			// Samurai Shodown II\0Shin Samurai Spirits - Haohmaru jigokuhen
	&BurnDrvSamSho3,			// Samurai Shodown III (set 1)\0Samurai Spirits - Zankurou musouken
	&BurnDrvSamSho3a,			// Samurai Shodown III (set 2)\0Samurai Spirits - Zankurou musouken\0Fighters Swords
	&BurnDrvSamSho4,			// Samurai Shodown IV - Amakusa's revenge\0Samurai Spirits - Amakusa kourin
	&BurnDrvsamsho5b,			// Samurai Shodown V (bootleg)\0Samurai Spirits Zero
	&BurnDrvsamsho5,			// Samurai Shodown V (set 1)\0Samurai Spirits Zero
	&BurnDrvsamsho5h,			// Samurai Shodown V (set 2)\0Samurai Spirits Zero
	&BurnDrvsamsh5sp,			// Samurai Shodown V Special (set 1, uncensored)\0Samurai Spirits Zero Special
	&BurnDrvsamsh5sh,			// Samurai Shodown V Special (set 2, censored)\0Samurai Spirits Zero Special
	&BurnDrvsamsh5sn,			// Samurai Shodown V Special (set 3, less censored)\0Samurai Spirits Zero Special
	&BurnDrvSamSho,				// Samurai Shodown\0Samurai Spirits
	&BurnDrvCpsWofa,			// Sangokushi II (921005 Asia)
	&BurnDrvCpsSlammast,		// Saturday Night Slam Masters (Slam Masters 930713 etc)
	&BurnDrvCpsSlammasu,		// Saturday Night Slam Masters (slam masters 930713 USA)
	&BurnDrvSavagere,			// Savage Reign\0Fu'un Mokushiroku - kakutou sousei
	&BurnDrvSengoku,			// Sengoku (set 1)\0Sengoku Denshou
	&BurnDrvSengokh,			// Sengoku (set 2)\0Sengoku Denshou
	&BurnDrvSengoku2,			// Sengoku 2\0Sengoku Denshou 2
	&BurnDrvSengoku3,			// Sengoku 3\0Sengoku Denshou 2001
	&BurnDrvCpsMercsj,			// Senjo no Ookami II (Ookami 2 900302 Japan)
	&BurnDrvmatrim,				// Shin gouketsuzi ichizoku - Toukon\0Matrimelee
	&BurnDrvShippuMD,			// Shippu Mahou Daisakusen - kingdom grandprix (Japan)
	&BurnDrvshocktro,			// Shock Troopers (set 1)
	&BurnDrvShocktra,			// Shock Troopers (set 2)
	&BurnDrvshocktr2,			// Shock Troopers - 2nd squad
	&BurnDrvSnowbroj,			// Snow Bros. - Nick & Tom (Japan)
	&BurnDrvSnowbros,			// Snow Bros. - Nick & Tom (set 1)
	&BurnDrvSnowbroa,			// Snow Bros. - Nick & Tom (set 2)
	&BurnDrvSnowbrob,			// Snow Bros. - Nick & Tom (set 3)
	&BurnDrvSnowbroc,			// Snow Bros. - Nick & Tom (set 4)
	&BurnDrvSnowbro2,			// Snow Bros. 2 - with new elves
	&BurnDrvSnowbro3,			// Snow Brothers 3 - Magical Adventure
	&BurnDrvSocbrawl,			// Soccer Brawl
	&BurnDrvSStriker,			// Sorcer Striker (World)
	&BurnDrvSStrikrA,			// Sorcer Striker (World, alt)
	&BurnDrvspinmast,			// Spin Master\0Miracle Adventure
	&BurnDrvStakwin,			// Stakes Winner
	&BurnDrvStakwin2,			// Stakes Winner 2
	&BurnDrvCpsSfach,			// Street Fighter Alpha (950727 CPS Changer)
	&BurnDrvCpsSfar3,			// Street Fighter Alpha - warriors' dreams (950605 Euro)
	&BurnDrvCpsSfar2,			// Street Fighter Alpha - warriors' dreams (950627 Euro)
	&BurnDrvCpsSfau,			// Street Fighter Alpha - warriors' dreams (950627 USA)
	&BurnDrvCpsSfar1,			// Street Fighter Alpha - warriors' dreams (950718 Euro)
	&BurnDrvCpsSfa,				// Street Fighter Alpha - warriors' dreams (950727 Euro)
	&BurnDrvCpsSfa2,			// Street Fighter Alpha 2 (960306 USA)
	&BurnDrvCpsSfa3b,			// Street Fighter Alpha 3 (980629 Brazil)
	&BurnDrvCpsSfa3r1,			// Street Fighter Alpha 3 (980629 USA)
	&BurnDrvCpsSfa3,			// Street Fighter Alpha 3 (980904 USA)
	&BurnDrvCpsSf2ua,			// Street Fighter II - the world warrior (910206 USA)
	&BurnDrvCpsSf2eb,			// Street Fighter II - the world warrior (910214 etc)
	&BurnDrvCpsSf2ja,			// Street Fighter II - the world warrior (910214 Japan)
	&BurnDrvCpsSf2ub,			// Street Fighter II - the world warrior (910214 USA)
	&BurnDrvCpsSf2ue,			// Street Fighter II - the world warrior (910228 USA)
	&BurnDrvCpsSf2jc,			// Street Fighter II - the world warrior (910306 Japan)
	&BurnDrvCpsSf2ud,			// Street Fighter II - the world warrior (910318 USA)
	&BurnDrvCpsSf2uf,			// Street Fighter II - the world warrior (910411 USA)
	&BurnDrvCpsSf2,				// Street Fighter II - the world warrior (910522 etc)
	&BurnDrvCpsSf2ui,			// Street Fighter II - the world warrior (910522 USA)
	&BurnDrvCpsSf2uk,			// Street Fighter II - the world warrior (911101 USA)
	&BurnDrvCpsSf2j,			// Street Fighter II - the world warrior (911210 Japan)
	&BurnDrvCpsSf2accp2,		// Street Fighter II' - champion edition (Hack - Accelerator Pt.II)
	&BurnDrvCpsKouryu,			// Street Fighter II' - champion edition (Hack - kouryu)
	&BurnDrvCpsSf2m2,			// Street Fighter II' - champion edition (Hack - M-2)
	&BurnDrvCpsSf2m4,			// Street Fighter II' - champion edition (Hack - M-4)
	&BurnDrvCpsSf2m5,			// Street Fighter II' - champion edition (Hack - M-5)
	&BurnDrvCpsSf2m6,			// Street Fighter II' - champion edition (Hack - M-6)
	&BurnDrvCpsSf2m7,			// Street Fighter II' - champion edition (Hack - M-7)
	&BurnDrvCpsSf2rb,			// Street Fighter II' - champion edition (Hack - Rainbow set 1)
	&BurnDrvCpsSf2rb2,			// Street Fighter II' - champion edition (Hack - Rainbow set 2)
	&BurnDrvCpsSf2red,			// Street Fighter II' - champion edition (Hack - Red Wave)
	&BurnDrvCpsSf2v004,			// Street Fighter II' - champion edition (Hack - V004)
	&BurnDrvCpsSf2yyc,			// Street Fighter II' - champion edition (Hack - YYC)
	&BurnDrvCpsSf2ce,			// Street Fighter II' - champion edition (street fighter 2' 920313 etc)
	&BurnDrvCpsSf2ceua,			// Street Fighter II' - champion edition (street fighter 2' 920313 USA)
	&BurnDrvCpsSf2cej,			// Street Fighter II' - champion edition (street fighter 2' 920513 Japan)
	&BurnDrvCpsSf2ceub,			// Street Fighter II' - champion edition (street fighter 2' 920513 USA)
	&BurnDrvCpsSf2ceuc,			// Street Fighter II' - champion edition (street fighter 2' 920803 USA)
	&BurnDrvCpsSf2hf,			// Street Fighter II' - hyper fighting (street fighter 2' T 921209 ETC)
	&BurnDrvCpsSf2t,			// Street Fighter II' - hyper fighting (street fighter 2' T 921209 USA)
	&BurnDrvCpsSf2tj,			// Street Fighter II' Turbo - hyper fighting (street fighter 2' T 921209 Japan)
	&BurnDrvCpsSfzjr2,			// Street Fighter Zero (950605 Japan)
	&BurnDrvCpsSfza,			// Street Fighter Zero (950627 Asia)
	&BurnDrvCpsSfzh,			// Street Fighter Zero (950627 Hispanic)
	&BurnDrvCpsSfzjr1,			// Street Fighter Zero (950627 Japan)
	&BurnDrvCpsSfzbr1,			// Street Fighter Zero (950727 Brazil)
	&BurnDrvCpsSfzj,			// Street Fighter Zero (950727 Japan)
	&BurnDrvCpsSfzch,			// Street Fighter Zero (951020 CPS Changer)
	&BurnDrvCpsSfzb,			// Street Fighter Zero (951109 Brazil)
	&BurnDrvCpsSfz2a,			// Street Fighter Zero 2 (960227 Asia)
	&BurnDrvCpsSfz2j,			// Street Fighter Zero 2 (960227 Japan)
	&BurnDrvCpsSfz2n,			// Street Fighter Zero 2 (960229 Oceania)
	&BurnDrvCpsSfz2br1,			// Street Fighter Zero 2 (960304 Brazil)
	&BurnDrvCpsSfz2h,			// Street Fighter Zero 2 (960304 Hispanic)
	&BurnDrvCpsSfz2b,			// Street Fighter Zero 2 (960531 Brazil)
	&BurnDrvCpsSfz2aj,			// Street Fighter Zero 2 Alpha (960805 Japan)
	&BurnDrvCpsSfz2ab,			// Street Fighter Zero 2 Alpha (960813 Brazil)
	&BurnDrvCpsSfz2ah,			// Street Fighter Zero 2 Alpha (960813 Hispanic)
	&BurnDrvCpsSfz2aa,			// Street Fighter Zero 2 Alpha (960826 Asia)
	&BurnDrvCpsSfz3jr2,			// Street Fighter Zero 3 (980629 Japan)
	&BurnDrvCpsSfz3ar1,			// Street Fighter Zero 3 (980701 Asia)
	&BurnDrvCpsSfz3jr1,			// Street Fighter Zero 3 (980727 Japan)
	&BurnDrvCpsSfz3a,			// Street Fighter Zero 3 (980904 Asia)
	&BurnDrvCpsSfz3j,			// Street Fighter Zero 3 (980904 Japan)
	&BurnDrvStrHoop,			// Street Hoop\0Street Slam\0Dunk Dream
	&BurnDrvCpsStrider,			// Strider (US set 1)
	&BurnDrvCpsStridrua,		// Strider (US set 2)
	&BurnDrvCpsStriderj,		// Strider Hiryu (Japan set 1)
	&BurnDrvCpsStridrja,		// Strider Hiryu (Japan set 2)
	&BurnDrvs1945p,				// Strikers 1945 plus
	&BurnDrvSdodgeb,			// Super Dodge Ball\0Kunio no Nekketsu Toukyuu Densetsu
	&BurnDrvCpsSgemfa,			// Super Gem Fighter Mini Mix (970904 Asia)
	&BurnDrvCpsSgemfh,			// Super Gem Fighter Mini Mix (970904 Hispanic)
	&BurnDrvCpsSgemf,			// Super Gem Fighter Mini Mix (970904 USA)
	&BurnDrvSupmodel,			// Super Model
	&BurnDrvCpsSmbombr1,		// Super Muscle Bomber - the international blowout (940808 Japan)
	&BurnDrvCpsSmbomb,			// Super Muscle Bomber - the international blowout (940831 Japan)
	&BurnDrvCpsSpf2ta,			// Super Puzzle Fighter II Turbo (Super Puzzle Fighter 2 Turbo 960529 Asia)
	&BurnDrvCpsSpf2t,			// Super Puzzle Fighter II Turbo (Super Puzzle Fighter 2 Turbo 960620 USA)
	&BurnDrvCpsSpf2xj,			// Super Puzzle Fighter II X (Super Puzzle Fighter 2 X 960531 Japan)
	&BurnDrvSsideki2,			// Super Sidekicks 2 - the world championship\0Tokuten Ou 2 - real fight football
	&BurnDrvSsideki3,			// Super Sidekicks 3 - the next glory\0Tokuten Ou 3 - eikoue no michi
	&BurnDrvSsideki,			// Super Sidekicks\0Tokuten Ou
	&BurnDrvCpsSsf2jr2,			// Super Street Fighter II - the new challengers (super street fighter 2 930910 Japan)
	&BurnDrvCpsSsf2,			// Super Street Fighter II - the new challengers (super street fighter 2 930911 etc)
	&BurnDrvCpsSsf2jr1,			// Super Street Fighter II - the new challengers (super street fighter 2 930911 Japan)
	&BurnDrvCpsSsf2u,			// Super Street Fighter II - the new challengers (super street fighter 2 930911 USA)
	&BurnDrvCpsSsf2ar1,			// Super Street Fighter II - the new challengers (super street fighter 2 930914 Asia)
	&BurnDrvCpsSsf2a,			// Super Street Fighter II - the new challengers (super street fighter 2 931005 Asia)
	&BurnDrvCpsSsf2j,			// Super Street Fighter II - the new challengers (super street fighter 2 931005 Japan)
	&BurnDrvCpsSsf2tbr1,		// Super Street Fighter II - the tournament battle (930911 etc)
	&BurnDrvCpsSsf2tbj,			// Super Street Fighter II - the tournament battle (930911 Japan)
	&BurnDrvCpsSsf2tb,			// Super Street Fighter II - the tournament battle (931119 etc)
	&BurnDrvCpsSsf2ta,			// Super Street Fighter II Turbo (super street fighter 2 X 940223 Asia)
	&BurnDrvCpsSsf2t,			// Super Street Fighter II Turbo (super street fighter 2 X 940223 etc)
	&BurnDrvCpsSsf2tur1,		// Super Street Fighter II Turbo (super street fighter 2 X 940223 USA)
	&BurnDrvCpsSsf2tu,			// Super Street Fighter II Turbo (super street fighter 2 X 940323 USA)
	&BurnDrvCpsSsf2xj,			// Super Street Fighter II X - grand master challenge (super street fighter 2 X 940223 Japan)
	&BurnDrvsvcpcb,				// SvC Chaos - SNK vs Capcom (JAMMA PCB, set 1)
	&BurnDrvsvcpcba,			// SvC Chaos - SNK vs Capcom (JAMMA PCB, set 2)
	&BurnDrvsvc,				// SvC Chaos - SNK vs Capcom (MVS)
	&BurnDrvsvcboot,			// SvC Chaos - SNK vs Capcom (MVS, bootleg)
	&BurnDrvsvcplus,			// SvC Chaos - SNK vs Capcom Plus (bootleg, set 1)
	&BurnDrvsvcplusa,			// SvC Chaos - SNK vs Capcom Plus (bootleg, set 2)
	&BurnDrvsvcsplus,			// SvC Chaos - SNK vs Capcom Super Plus (bootleg)
	&BurnDrvMOSyougi,			// Syougi No Tatsujin - master of syougi
	&BurnDrvTws96,				// Tecmo World Soccer '96
	&BurnDrvTekiPaki,			// Teki Paki
	&BurnDrvCpsDwj,				// Tenchi wo Kurau (Japan)
	&BurnDrvCpsWofj,			// Tenchi wo Kurau II - Sekiheki no Tatakai (921031 Japan)
	&BurnDrvBerlwall,			// The Berlin Wall
	&BurnDrvBerlwalt,			// The Berlin Wall (bootleg ?)
	&BurnDrvIrrmaze,			// The Irritating Maze\0Ultra Denryu Iraira Bou
	&BurnDrvCpsKod,				// The King of Dragons (910711 etc)
	&BurnDrvCpsKodj,			// The King of Dragons (Japan 910805)
	&BurnDrvCpsKodu,			// The King of Dragons (US 910910)
#if defined FBA_DEBUG
	&BurnDrvCpsKodb,			// The King of Dragons [No Sprites, NOT WORKING]
#endif
	&BurnDrvKof94,				// The King of Fighters '94
	&BurnDrvKof95,				// The King of Fighters '95 (set 1)
	&BurnDrvKof95a,				// The King of Fighters '95 (set 2)
	&BurnDrvKof96,				// The King of Fighters '96 (set 1)
	&BurnDrvKof96h,				// The King of Fighters '96 (set 2)
	&BurnDrvKof97,				// The King of Fighters '97 (set 1)
	&BurnDrvKof97a,				// The King of Fighters '97 (set 2)
	&BurnDrvKof97p,				// The King of Fighters '97 Plus (bootleg)
	&BurnDrvKof98k,				// The King of Fighters '98 - the slugfest (korean release)\0King of Fighters '98 - dream match never ends
	&BurnDrvKof98n,				// The King of Fighters '98 - the slugfest (not encrypted)\0King of Fighters '98 - dream match never ends
	&BurnDrvKof98,				// The King of Fighters '98 - the slugfest\0King of Fighters '98 - dream match never ends
//	&BurnDrvKof98a,				// The King of Fighters '98 - the slugfest\0King of Fighters '98 - dream match never ends [Alternate version]
	&BurnDrvkof99e,				// The King of Fighters '99 - millennium battle (earlier)
	&BurnDrvkof99n,				// The King of Fighters '99 - millennium battle (not encrypted)
	&BurnDrvkof99p,				// The King of Fighters '99 - millennium battle (prototype)
	&BurnDrvkof99,				// The King of Fighters '99 - millennium battle (set 1)
	&BurnDrvkof99a,				// The King of Fighters '99 - millennium battle (set 2)
	&BurnDrvkof10th,			// The King of Fighters 10th Anniversary (bootleg)
	&BurnDrvkf2k5uni,			// The King of Fighters 10th Anniversary 2005 Unique (bootleg)
	&BurnDrvkf10thep,			// The King of Fighters 10th Anniversary Extra Plus (bootleg)
	&BurnDrvkof2000,			// The King of Fighters 2000
	&BurnDrvkof2000n,			// The King of Fighters 2000 (not encrypted)
	&BurnDrvkof2001,			// The King of Fighters 2001 (set 1)
	&BurnDrvkof2001h,			// The King of Fighters 2001 (set 2)
	&BurnDrvkof2002,			// The King of Fighters 2002 - challenge to ultimate battle
	&BurnDrvkf2k2mp,			// The King of Fighters 2002 Magic Plus (bootleg)
	&BurnDrvkf2k2mp2,			// The King of Fighters 2002 Magic Plus II (bootleg)
	&BurnDrvkf2k2pls,			// The King of Fighters 2002 Plus (bootleg, set 1)
	&BurnDrvkf2k2pla,			// The King of Fighters 2002 Plus (bootleg, set 2)
	&BurnDrvkf2k3bl,			// The King of Fighters 2003 (bootleg, set 1)
	&BurnDrvkf2k3bla,			// The King of Fighters 2003 (bootleg, set 2)
	&BurnDrvkf2k3pcb,			// The King of Fighters 2003 (Japan, JAMMA PCB)
	&BurnDrvkof2003,			// The King of Fighters 2003 (MVS)
	&BurnDrvkf2k3pl,			// The King of Fighters 2004 Plus / Hero (bootleg)
	&BurnDrvkf2k3upl,			// The King of Fighters 2004 Ultra Plus (bootleg)
	&BurnDrvkof2k4se,			// The King of Fighters Special Edition 2004 (bootleg)
	&BurnDrvlastblad,			// The Last Blade (set 1)\0Bakumatsu Roman Gekka No Kenshi
	&BurnDrvlastbldh,			// The Last Blade (set 2)\0Bakumatsu Roman Gekka No Kenshi
	&BurnDrvlastbld2,			// The Last Blade 2\0Bakumatsu Roman Dai Ni Maku - Gekka No Kenshi
	&BurnDrvlastsold,			// The Last Soldier
	&BurnDrvCpsPunisher,		// The Punisher (930422 etc)
	&BurnDrvCpsPunishrj,		// The Punisher (930422 Japan)
	&BurnDrvCpsPunishru,		// The Punisher (930422 USA)
	&BurnDrvSuperspy,			// The Super Spy
	&BurnDrvSsideki4,			// The Ultimate 11 - SNK football championship\0Tokuten Ou - honoo no libero
	&BurnDrvWintbob,			// The Winter Bobble (bootleg)
	&BurnDrvTRally,				// Thrash Rally
	&BurnDrvCps3wonders,		// Three Wonders (wonder 3 910520 etc)
	&BurnDrvCps3wonderu,		// Three Wonders (wonder 3 910520 USA)
	&BurnDrvTheroes,			// Thunder Heroes
	&BurnDrvtophntr,			// Top Hunter - Roddy & Cathy (set 1)
	&BurnDrvtophunta,			// Top Hunter - Roddy & Cathy (set 2)
	&BurnDrvTpgolf,				// Top Player's Golf
	&BurnDrvToppyrap,			// Toppy & Rappy
	&BurnDrvTruxton2,			// Truxton II\0Tatsujin Oh
	&BurnDrvTruxton,			// Truxton\0Tatsujin
	&BurnDrvTwinadvk,			// Twin Adventure (Korea)
	&BurnDrvTwinadv,			// Twin Adventure (World)
	&BurnDrvTwinkle,			// Twinkle
	&BurnDrvTwinSpri,			// Twinklestar Sprites
	&BurnDrvCpsUnsquad,			// U.N. Squadron (US)
	&BurnDrvCpsCawingj,			// U.S. Navy (901012 Japan)
	&BurnDrvCpsUecology,		// Ultimate Ecology (931203 Japan)
	&BurnDrvUoPokoj,			// Uo Poko (Japan, ver. 1998 Feb 06)
	&BurnDrvVFive,				// V-Five (Japan)
	&BurnDrvVliner,				// V-Liner (set 1)
	&BurnDrvVlinero,			// V-Liner (set 2)
	&BurnDrvCpsVampjr1,			// Vampire - the night warriors (940630 Japan)
	&BurnDrvCpsVampj,			// Vampire - the night warriors (940705 Japan)
	&BurnDrvCpsVampja,			// Vampire - the night warriors (940705 Japan, alt)
	&BurnDrvCpsVhuntjr2,		// Vampire Hunter - darkstalkers' revenge (950302 Japan)
	&BurnDrvCpsVhuntjr1,		// Vampire Hunter - darkstalkers' revenge (950307 Japan)
	&BurnDrvCpsVhuntj,			// Vampire Hunter - darkstalkers' revenge (950316 Japan)
	&BurnDrvCpsVhunt2r1,		// Vampire Hunter 2 - darkstalkers revenge (970913 Japan)
	&BurnDrvCpsVhunt2,			// Vampire Hunter 2 - darkstalkers revenge (970929 Japan)
	&BurnDrvCpsVsava,			// Vampire Savior - the lord of vampire (970519 Asia)
	&BurnDrvCpsVsav,			// Vampire Savior - the lord of vampire (970519 Euro)
	&BurnDrvCpsVsavh,			// Vampire Savior - the lord of vampire (970519 Hispanic)
	&BurnDrvCpsVsavj,			// Vampire Savior - the lord of vampire (970519 Japan)
	&BurnDrvCpsVsavu,			// Vampire Savior - the lord of vampire (970519 USA)
	&BurnDrvCpsVsav2,			// Vampire Savior 2 - the lord of vampire (970913 Japan)
	&BurnDrvCpsVarthr1,			// Varth - operation thunderstorm (920612 etc)
	&BurnDrvCpsVarthu,			// Varth - operation thunderstorm (920612 USA)
	&BurnDrvCpsVarth,			// Varth - operation thunderstorm (920714 etc)
	&BurnDrvCpsVarthj,			// Varth - operation thunderstorm (920714 Japan)
	&BurnDrvViewpoin,			// Viewpoint
	&BurnDrvgowcaizr,			// Voltage Fighter - Gowcaizer\0Choujin Gakuen Gowcaizer
	&BurnDrvWakuwak7,			// Waku Waku 7
	&BurnDrvCpsWof,				// Warriors of Fate (921002 etc)
	&BurnDrvCpsWofu,			// Warriors of Fate (921031 USA)
	&BurnDrvCpsWillowje,		// Willow (Japan, English)
	&BurnDrvCpsWillowj,			// Willow (Japan, Japanese)
	&BurnDrvCpsWillow,			// Willow (US)
	&BurnDrvWJammers,			// Windjammers - flying disc game\0Flying Power Disc
	&BurnDrvCpsWonder3,			// Wonder 3 (910520 Japan)
	&BurnDrvWc90,				// World Cup '90 (set 1)
	&BurnDrvWc90a,				// World Cup '90 (set 2)
	&BurnDrvWc90t,				// World Cup '90 (trackball)
	&BurnDrvWH1,				// World Heroes (set 1)
	&BurnDrvWH1h,				// World Heroes (set 2)
	&BurnDrvWH2,				// World Heroes 2
	&BurnDrvWH2J,				// World Heroes 2 Jet
	&BurnDrvWHP,				// World Heroes Perfect
	&BurnDrvCpsXmcotajr,		// X-Men - children of the atom (941208 Japan, rent version)
	&BurnDrvCpsXmcotaa,			// X-Men - children of the atom (941217 Asia)
	&BurnDrvCpsXmcotaj1,		// X-Men - children of the atom (941217 Japan)
	&BurnDrvCpsXmcotaj,			// X-Men - children of the atom (941219 Japan)
	&BurnDrvCpsXmcota,			// X-Men - children of the atom (950105 Euro)
	&BurnDrvCpsXmcotau,			// X-Men - children of the atom (950105 USA)
	&BurnDrvCpsXmcotah,			// X-Men - children of the atom (950331 Hispanic)
	&BurnDrvCpsXmvsfjr2,		// X-Men vs Street Fighter (960909 Japan)
	&BurnDrvCpsXmvsfr1,			// X-Men vs Street Fighter (960910 Euro)
	&BurnDrvCpsXmvsfjr1,		// X-Men vs Street Fighter (960910 Japan)
	&BurnDrvCpsXmvsfar1,		// X-Men vs Street Fighter (960919 Asia)
	&BurnDrvCpsXmvsf,			// X-Men vs Street Fighter (961004 Euro)
	&BurnDrvCpsXmvsfh,			// X-Men vs Street Fighter (961004 Hispanic)
	&BurnDrvCpsXmvsfj,			// X-Men vs Street Fighter (961004 Japan)
	&BurnDrvCpsXmvsfur1,		// X-Men vs Street Fighter (961004 USA)
	&BurnDrvCpsXmvsfa,			// X-Men vs Street Fighter (961023 Asia)
	&BurnDrvCpsXmvsfb,			// X-Men vs Street Fighter (961023 Brazil)
	&BurnDrvCpsXmvsfu,			// X-Men vs Street Fighter (961023 USA)
	&BurnDrvThreein1semi,		// XESS - The New Revolution (SemiCom 3-in-1)
	&BurnDrvZedblade,			// Zed Blade\0Operation Ragnarok
	&BurnDrvZerowing,			// Zero Wing
	&BurnDrvzintrckb,			// Zintrick (hack / bootleg)\0Oshidashi Zentri
	&BurnDrvZipzap, 			// Zip & Zap
	&BurnDrvZupapa,				// Zupapa!
	
	&BurnDrvKaratblz,
	&BurnDrvTurbofrc,
	&BurnDrvSpinlbrk,
	&BurnDrvSpinlbru,
	&BurnDrvSpinlbrj,

	&BurnDrvGalpanic,
	&BurnDrvpgm,
	&BurnDrvOrlegend,
	&BurnDrvOrlegnde,
	&BurnDrvOrlegndc,
	&BurnDrvOrld111c,
	&BurnDrvOrld105k,
	&BurnDrvKov,
	&BurnDrvKov115,
	&BurnDrvKovj,
	&BurnDrvKovplus,
	&BurnDrvKovplusa,
	&BurnDrvdrgw2,
	&BurnDrvdrgw2c,
	&BurnDrvkillbld,
	&BurnDrvkillbldt,
	&BurnDrvraf102j,
	&BurnDrvpuzlstar,
	&BurnDrvphotoy2k,
	&BurnDrv1945kiii,
	&BurnDrvHook,
	&BurnDrvWwfwfest,
	&BurnDrvWwfwfsta,
	&BurnDrvWwfwfstb,
	&BurnDrvWwfwfstj,
	&BurnDrvhotdogst,
	&BurnDrvmetmqstr,
	&BurnDrvnmaster,
	&BurnDrvmazinger,
	&BurnDrvpwrinst2,
	&BurnDrvpwrins2j,
	&BurnDrvplegends,
	&BurnDrvplegendj,
	&BurnDrvTumblep,
	&BurnDrvTumbleb,
	&BurnDrvTumbleb2,
	&BurnDrvJumpkids,
	&BurnDrvMetlsavr,
	&BurnDrvPangpang,
	&BurnDrvSuprtrio,
	&BurnDrvHtchctch,
	&BurnDrvCookbib,
	&BurnDrvChokChok,
	&BurnDrvWlstar,
	&BurnDrvWondl96,
	&BurnDrvFancywld,
	&BurnDrvSdfight,
	&BurnDrvBcstry,
	&BurnDrvBcstrya,
	&BurnDrvSemibase,
	&BurnDrvDquizgo,
	&BurnDrvJumppop,
	&BurnDrvShadoww,
	&BurnDrvShadowwa,
	&BurnDrvGaiden,
	&BurnDrvRyukendn,
	&BurnDrvRyukenda,
	&BurnDrvWildfang,
	&BurnDrvTknight,
	&BurnDrvStratof,
	&BurnDrvRaiga,
	&BurnDrvDrgnbowl,
	&BurnDrvBurglarx,
	&BurnDrvMultchmp,
	&BurnDrvMultchmk,
	&BurnDrvHedpanic,
	&BurnDrvHedpanif,
	&BurnDrvMchampdx,
	&BurnDrvMchampda,
	&BurnDrvTangtang,
	&BurnDrvSwatpolc		
};
